gbdk-2020/gbdk-2020

gbdk-lib/include/gb/gb.h

Fix documentation error

---

gbdk-lib/examples/gb/Makefile
gbdk-lib/examples/gb/bcd.c
gbdk-lib/examples/gb/colorbar/make.bat
gbdk-lib/examples/gb/crash.c
gbdk-lib/examples/gb/dscan/make.bat
gbdk-lib/examples/gb/gb-dtmf/make.bat
gbdk-lib/include/bcd.h
gbdk-lib/include/gb/crash_handler.h
gbdk-lib/include/gb/gb.h
gbdk-lib/libc/asm/gbz80/_memcpy.s
gbdk-lib/libc/bcd.c
gbdk-lib/libc/gb/Makefile
gbdk-lib/libc/gb/crash_handler.s
gbdk-lib/libc/gb/crt0.s
gbdk-lib/libc/gb/global.s
gbdk-lib/libc/gb/pad.s

shorter and more optimal code; hints in gb.h allow better register allocation by SDCC - we might set that for all frequent asm functions.

optimized joypad routines; register usage hints; RST38 crash handler

---

gbdk-lib/include/bcd.h
gbdk-lib/include/ctype.h
gbdk-lib/include/gb/gb.h
gbdk-lib/include/gb/sgb.h
gbdk-lib/include/gbdk-lib.h
gbdk-lib/include/rand.h
gbdk-lib/include/stdio.h
gbdk-lib/include/stdlib.h
gbdk-lib/include/string.h
gbdk-lib/include/time.h

@Zal0 & @untoxa ,
Here are a bunch more doxygen header file comment updates.
There are no functional code changes in this PR, just comment edits (synced to latest develop).
In the future, any preference between big merged commits vs smaller commits? Single vs separate PRs?
Lastly, if anyone is feeling up to it, some fact-checking of the new descriptions wouldn't hurt. :)

Docs: Update and add doxygen compatible header file comments (no functional source code edits)

---

docs/config/gbdk-2020-doxyfile

This should improve the navigation categories. Changes Classes category to Data Structures, etc.

Docs: Turn on doxygen "Optimize for C output"

---

gbdk-lib/examples/gb/bgb_debug/Makefile
gbdk-lib/examples/gb/bgb_debug/bgb_debug.c
gbdk-lib/examples/gb/bgb_debug/make.bat

It could be a useful example to include since it's now part of the API.
Some of the code is from the GB forums post on the topic (toxa, zal0).

Examples: Add bgb debug example

---

gbdk-lib/include/bcd.h
gbdk-lib/include/gb/bgb_emu.h
gbdk-lib/include/gb/cgb.h
gbdk-lib/include/gb/console.h
gbdk-lib/include/gb/crash_handler.h
gbdk-lib/include/gb/drawing.h
gbdk-lib/include/gb/far_ptr.h
gbdk-lib/include/gb/font.h
gbdk-lib/include/gb/gb.h
gbdk-lib/include/gb/malloc.h
gbdk-lib/include/gb/sgb.h
gbdk-lib/include/stdio.h
gbdk-lib/include/time.h

No source changes, just comments. 
Does not include updated docs/ output to keep it more manageable.

Docs: Lots of doxygen formatted API header updates

---

gbdk-support/ihxcheck/ihx_file.c

Better handling of zero length and EOF records.

IHX Check: Discard zero length records

---

gbdk-lib/include/gb/gb.h

Update docs for waitpad

---

README.md

Wasn't sure whether or not to mention ZGB in there.

Readme: Add discord server link

---

gbdk-lib/examples/gb/sound/readme.md
gbdk-lib/examples/gb/sound/sound.c

Merge initial version of improved sound example project. It is more user friendly. 
Required a couple improvements for use with GBDK-2020
* Fix unitialized vars
* Change cursor character to work with reduced default font characters in gbdk 4.0.2
* Remove compiler workaround that is no longer needed
* Fix const warning
* Add readme.md with instructions

Example: Sound sample: merge in improvements from Zal0's repo (various contributors)

---

gbdk-support/lcc/lcc.c

Support flags according to SDCC [[r12062]](https://sourceforge.net/p/sdcc/code/12062/)
This is in preparation for the 4.1.0 release candidate, which should arrive in about a week.

Update accepted flags for makebin

---

README.md
docs/pages/banking_mbcs.md
docs/pages/toolchain.md
gbdk-support/ChangeLog
gbdk-support/README

- Docs: Add links between bank section about errors and related FAQ section
- Add link for Docs "Getting Started" to git repo root Readme.md
- Changelog: Fix "gbdk3-4.x" naming to just "gbdk-4.x"
- Update README that gets placed in root of installed GBDK folder

Docs updates

---

docs/pages/release_notes.md
gbdk-lib/include/gb/gbdecompress.h
gbdk-lib/include/gb/metasprites.h

More doc updates. More may come, so better to wait and regenerate docs later.
- Initial release notes (docs markdown version)
- Documentation for gbdecompress

Docs updates - initial release notes (docs version) and gbcompress header comments

---

gbdk-lib/examples/gb/template_minimal/Makefile
gbdk-lib/examples/gb/template_subfolders/Makefile

* Fix minimal-template makefile for ASM sources (typo)
* Improve Flags var for LCC in subfolder-template

Examples: Fix / Improve template makefiles

---

docs/pages/06_toolchain.md
docs/pages/08_faq.md

Also add a FAQ entry.
Addresses remaining topics mentioned in #172 
Main docs are not regenerated (can happen later)

Docs: improve documentation of png2mtspr graphics conversion process

---

docs/pages/04_coding_guidelines.md
gbdk-lib/include/ctype.h
gbdk-lib/libc/isalpha.c
gbdk-lib/libc/isdigit.c
gbdk-lib/libc/islower.c
gbdk-lib/libc/isspace.c
gbdk-lib/libc/isupper.c

Switch the few functions in lib from `BOOLEAN` (currently uses signed char [INT8]) to `bool` (`stdbool.h`).
Also recommend it in the docs coding guidelines.
Made a simple test app to check the changed ctype functions, they appeared to still work ok.

lib: Use stdbool

---

gbdk-support/bankpack/files.c
gbdk-support/bankpack/files.h
gbdk-support/bankpack/obj_data.c
gbdk-support/bankpack/obj_data.h
gbdk-support/gbcompress/files.c
gbdk-support/gbcompress/files.h
gbdk-support/gbcompress/files_c_source.c
gbdk-support/gbcompress/files_c_source.h
gbdk-support/gbcompress/main.c
gbdk-support/lcc/Makefile
gbdk-support/lcc/lcc.c

Building on MacOS: Clear up misc warnings
* Bankpack
* gbcompress
* lcc
lcc: fix possible order of operations bug

Building on MacOS: Fix misc warnings

---

Makefile

- change gbdk-lib-install from hardwired to port and platform loops
- centralize port and platform list at top of makefile

makefile: improve port and platform handling

---

gbdk-support/png2asset/png2asset.cpp

- Fix for new code
- Change fixups in existing code to unsigned ints

Support: png2asset: fix size_t to int printf() conversion warnings

---

docs/pages/05_banking_mbcs.md
docs/pages/06_toolchain.md
docs/pages/06b_supported_consoles.md
docs/pages/08_faq.md
docs/pages/09_migrating_new_versions.md
docs/pages/10_release_notes.md
docs/pages/20_toolchain_settings.md
docs/pages/docs_index.md
gbdk-lib/include/gb/metasprites.h
gbdk-lib/include/sms/metasprites.h
gbdk-support/lcc/lcc.c

Some updates covering banks, cross platform support, png2mtspr renaming to png2asset, etc. Lots more to do.

Docs: Start of updates for 4.0.5 release

---

docs/pages/03_using_gbdk.md
gbdk-lib/include/gb/isr.h

- Improve ISR_VECTOR() description
- Mention it under the custom ISR dispatcher section

Docs: ISR_VECTOR() and related

---

docs/pages/05_banking_mbcs.md
docs/pages/06b_supported_consoles.md
gbdk-lib/include/gb/gb.h

- Updates for new SWITCH_ROM and SWITCH_RAM
- Cross Platform: AP compatibility

Docs: 4.0.5 updates

---

gbdk-lib/include/gb/gb.h
gbdk-lib/include/gb/hardware.h
gbdk-lib/include/sms/gbdecompress.h
gbdk-lib/include/stdlib.h

- Update descriptions for some flags and bits in hardware.h
- Add description of return value for gbdecompress
- Document DMG_PALETTE and misc cpu types in gb.h
- Updates for stdlib integer conversion

Docs: updates for 4.0.5

---

Makefile
docs/config/gbdk-2020-doxyfile
docs/pages/01_getting_started.md
docs/pages/10_release_notes.md
gbdk-lib/include/asm/gbz80/string.h

- Add version number to front of PDF and HTML docs(controlled my version in root makefile)
- Little improvements to memcmp() and strncmp()

Updates for 4.0.6

---

.github/workflows/gbdk_build_examples.yml

Update Build Examples action to also build using win32 binaries

CI/CD: Build and Build Examples: Win x32 build

---

docs/pages/01_getting_started.md
docs/pages/02_links_and_tools.md
docs/pages/03_using_gbdk.md
docs/pages/04_coding_guidelines.md
docs/pages/05_banking_mbcs.md
docs/pages/06_toolchain.md
docs/pages/06b_supported_consoles.md
docs/pages/07_sample_programs.md
docs/pages/08_faq.md

Fixed some small stuff here and there in the documentation files.

Fixed typos in docs

---

docs/pages/06b_supported_consoles.md

- Updates to supported consoles page

Docs: MSX: Basic info for MSX DOS port/platform

---

gbdk-support/png2asset/png2asset.cpp

The option -keep_duplicate_tiles can be used to have it export all tiles, without removing duplicates.
This could for example be used together with -map and -tiles_only, to get a list of all tiles in your image. This can then be used with draw_image() to display it.

Add -keep_duplicate_tiles as option to png2asset

---

gbdk-support/png2asset/png2asset.cpp

- Also reorder keep_duplciate_tiles if statements so short block is on top

png2asset: fixup spaces to tabs, remove printf warnings

---

gbdk-support/png2asset/png2asset.cpp

- centralize and simplify handling code a little, clarify naming some

png2asset: enforce -max_palettes with -keep_palette

---

docs/pages/03_using_gbdk.md
docs/pages/04_coding_guidelines.md
docs/pages/06_toolchain.md
docs/pages/20_toolchain_settings.md
gbdk-support/gbcompress/files_c_source.c
gbdk-support/png2asset/png2asset.cpp

This PR fixes a few more typos :)

[docs] Fix more typos

---

docs/config/github-markdown-theme/doxygen_extra.css
docs/pages/05_banking_mbcs.md

- Improve formatting of old one
- Improve doxygen markdown css

Docs: Add a nicer table for MBCs, not sure if it's entirely better so keeping old one too

---

gbdk-lib/libc/targets/mos6502/nes/crt0.s

* Remove redundant ZP variable __crt0_drawListPosR, and reclaim 8 cycles in vblank handler
* Add VRAM_BUFFER_LOCK / VRAM_BUFFER_UNLOCK macros, for slightly shorter / more descriptive code
* Rewrite _writeNametableByte to prefer adding bytes to a previous horizontal stripe when possible, adding ZP variable .crt0_textStringBegin to store last stripe position
* Introduce ZP variable .crt0_forced_blanking to keep track of when system is in forced blanking mode
* Add code path in _writeNametableByte to write characters directly to PPUDATA when in forced blanking mode, to make printf work when display is off
* Make sure to initialize __crt0_drawListNumDelayCycles_x8 at reset to prevent 1-frame glitch
* Fix bug with DoUpdateVRAM_invalid_loop setting __crt0_drawListNumDelayCycles_x8 to zero …

NES: Refactor / optimize VRAM transfer buffer handling:

---

docs/pages/04_coding_guidelines.md
docs/pages/08_faq.md
docs/pages/09_migrating_new_versions.md
gbdk-lib/include/gb/drawing.h
gbdk-lib/include/gb/gb.h

- Details about color() in drawing.h, more gbz80 to sm83 warning info, More port warnings
- More about calling convention changes

Docs: Details about SHOW_WIN, calling conventions, sm83 PORT name

---

gbdk-lib/examples/cross-platform/rle_map/Makefile
gbdk-lib/examples/cross-platform/rle_map/src/main.c

* Update main.c to always write just one column ahead
* Add blanking of leftmost screen column when screen buffer width is equal to screen width
* Enable sms building in Makefile

SMS: Enable rle_map example for sms

---

docs/pages/05_banking_mbcs.md
docs/pages/10_release_notes.md
docs/pages/20_toolchain_settings.md
gbdk-lib/include/asm/mos6502/types.h
gbdk-lib/include/asm/sm83/types.h
gbdk-lib/include/asm/z80/types.h
gbdk-lib/include/gb/gb.h

- Docs: isr handler updates + some release notes
- Docs: MBC updates and lcc -E flag

Docs: 4.1.0: isr handler updates, release notes, MBC updates

---

docs/pages/06b_supported_consoles.md

- Reorganize sections a little
- Document hardware differences

Docs: Mega Duck vs Game Boy Hardware differences

---

gbdk-lib/examples/cross-platform/metasprites/src/metasprites.c

* Make reverse_bits lookup table a const array
* Move tile upload/flipping into its own function load_and_duplicate_sprite_tile_data
* Replace joypad_ex polling with simpler joypad routine, as no need for 2-player support

Code Review changes to cross-platform/metasprites

---

Makefile
docs/config/github-markdown-theme/doxygen_extra.css
docs/doxygen_search_combined.html
docs/doxygen_search_override.js

Docs: patch in an improved doxygen substring search
- Does full substring match instead of only matching items with same starting sequence
- Unclear how compatible this will be across doxygen versions

Docs: 4.2.0 doxy search improve

---

docs/pages/01_getting_started.md
docs/pages/08_faq.md
gbdk-lib/include/gb/gb.h
gbdk-lib/include/gb/metasprites.h
gbdk-lib/include/msx/metasprites.h
gbdk-lib/include/msx/msx.h
gbdk-lib/include/nes/metasprites.h
gbdk-lib/include/nes/nes.h
gbdk-lib/include/sms/metasprites.h
gbdk-lib/include/sms/sms.h

- Add macOS unsigned binary workaround to FAQ and update phrasing a little
- Update metasprite info for base_props parameter and centralize long description in GB header file, link others to it

Docs 4.2.0

---

gbdk-support/png2asset/png2asset.cpp

- Mostly based on version by @tumetuoppi in https://github.com/tumetuoppi/gbdk-2020/commit/58f4e077009a6c40066f25db1908aad6a535f25b with minor changes

png2asset: option to not export palette data ( -no_palettes ) #345

---

Makefile
gbdk-support/makebin/Makefile

Also fix name in gbdk makebin Makefile

Build: copy libgcc_s_dw2-1.dll for windows 32 bit

---

README.md

Simple spelling fix i just saw while passing by, great work all!

fix: spelling fix

---

gbdk-lib/examples/gb/gbcheck/Makefile
gbdk-lib/examples/gb/gbcheck/gbcheck.c

The makefile should work. If not, tell me.

Example program idea: Program that detects which Game Boy the ROM is being run on

---

gbdk-lib/libc/targets/mos6502/nes/vram_transfer_buffer.s

* Move code for setting vertical-write bit in PPUCTRL and PPUADDR from .ppu_stripe_begin into .ppu_stripe_begin_horizontal / _vertical, for faster code
* Make sure to update _shadow_PPUCTRL before PPUCTRL, to prevent NMI interrupting and changing vertical-write bit in PPUCTRL

NES: Fix bug with vertical stripes not working in direct mode

---

gbdk-lib/libc/targets/mos6502/nes/crt0.s

* Decrease maximum number of bytes in a stripe from 64 to 32
* Replace lookup table ProcessDrawList_NumBytesToAddress with equivalent code
* Re-organize tables / subroutines in _CODE to remove empty space between aligned sections

NES: Optimize CRT0 space, saving ~0.5 kB of fixed-bank ROM in _CODE

---

gbdk-lib/examples/cross-platform/libc_string/Makefile
gbdk-lib/examples/cross-platform/libc_string/Makefile.targets
gbdk-lib/examples/cross-platform/libc_string/src/libc_string.c

* Make test execute strlen, strcmp/strncmp, strcpy/strncpy and strcat/strncat

Add cross-platform test for exercising string functions in string.h

---

gbdk-lib/include/gb/cgb.h
gbdk-lib/include/msx/msx.h
gbdk-lib/include/nes/nes.h
gbdk-lib/include/sms/sms.h

* Update set_bkg_palette and set_sprite_palette in gbdk-lib/include/gb/cgb.h
* Update set_bkg_palette and set_sprite_palette in gbdk-lib/include/nes/nes.h

Make set_bkg_palette and set_sprite_palette take const pointers

---

docs/pages/03_using_gbdk.md
docs/pages/06b_supported_consoles.md
docs/pages/09_migrating_new_versions.md
docs/pages/10_release_notes.md

- Platform summaries: add tile/attribute grid size entries
- Link NES section from a couple places
- Move SMS/GG RAM Bank note

Docs: 4.2.0 supported console updates

---

gbdk-lib/include/gb/gb.h
gbdk-lib/include/nes/nes.h
gbdk-lib/include/sms/sms.h

I have updated the docs for set_sprite_prop() as they were a little bit out.
I'm quite interested in updating some other documentation, would following updates be accepted? Is there any preferred format?

Updated documentation for set_sprite_prop()

---

docs/pages/08_faq.md
gbdk-lib/include/gb/gb.h
gbdk-lib/include/nes/nes.h

docs: set_sprite_prop() Remove non-constant example and change constant example to use bitwise OR instead of addition

Docs: minor changes to merged PR, add some warning notes to FAQ

---

gbdk-support/png2asset/image_data.cpp
gbdk-support/png2asset/main.cpp

- png2asset: fix warning "statement has no effect"
- png2asset: fix garbage in unused colors in each palette

png2asset: palette and warning fixes

---

gbdk-lib/libc/targets/mos6502/font.s
gbdk-lib/libc/targets/mos6502/mode.s
gbdk-lib/libc/targets/mos6502/nes/crt0.s

* Remove unused variable __crt0_NMI_Done
* Move .mode variable from ZP to BSS

NES: Trim away 2 bytes of zeropage

---

gbdk-lib/examples/cross-platform/banks_farptr/src/bank2code.c
gbdk-lib/examples/cross-platform/banks_farptr/src/banks_farptr.c

* Add new function some_bank2_proc2 with keywords __banked and REENTRANT in bank2code.c
* Add direct call to function in banks_farptr.c

Add code to test re-entrant banked call in examples/cross-platform/banks_farptr

---

docs/pages/02_links_and_tools.md
docs/pages/05_banking_mbcs.md
docs/pages/08_faq.md
gbdk-lib/examples/gb/hblank_copy/src/main.c
gbdk-lib/examples/gb/hicolor/src/gbc_hicolor.c
gbdk-lib/examples/gb/hicolor/src/main.c
gbdk-lib/examples/sms/wav_sample/src/samptest.c
gbdk-lib/include/gb/gb.h
gbdk-lib/include/gb/hardware.h
gbdk-lib/include/gb/hblankcpy.h
gbdk-lib/include/gb/metasprites.h
gbdk-lib/include/gbdk/incbin.h
gbdk-lib/include/rand.h

- Remove hUGEbuild link
- VScode c config for better GBDK var detection
- Recommend CURRENT_BANK over _current_bank
- FAQ entry about HIDE_LEFT_COLUMN
- More info about using the add_JOY() interrupt and improve docs for some linked constants
- Improve docs for reset()
- Improve docs for hblank_copy()
- Improve docs for base_prop metasprite parameter
- Improve docs for initrand() a bit

Doc improvements

---

.github/workflows/gbdk_build_and_package.yml

- Also update upload action due to deprecation

CI/CD: build and package: sdcc 14635

---

.github/workflows/gbdk_build_examples.yml

- Also update upload action due to deprecation

CI/CD: build examples: sdcc 14635

---

docs/pages/10_release_notes.md
gbdk-lib/include/gb/gb.h
gbdk-lib/include/nes/nes.h
gbdk-lib/include/sms/sms.h

- set_palette() for SMS/GG
- Clarify display_off behavior for GB and NES
- More historical GBDK release notes

Docs: set_palette() for SMS/GG, clarify display_off behavior for GB and NES

---

gbdk-support/png2asset/export.cpp

- Also centralize some of the tileset and palette export size calculations so they are easier to maintain
- There appears to be some dead use_structs export code noted with `// TODO: FIXME: `

png2asset: zgb special case (source_tileset + use_structs): include source tileset and palette data

---

Makefile
docs/ChangeLog
docs/pages/06_toolchain.md
docs/pages/09_migrating_new_versions.md
docs/pages/10_release_notes.md
docs/pages/20_toolchain_settings.md
gbdk-lib/examples/cross-platform/joytest/src/joytest.c
gbdk-lib/include/gb/gb.h
gbdk-lib/include/gbdk/version.h
gbdk-lib/include/sms/hardware.h
gbdk-support/png2asset/process_arguments.cpp

- Start of changelist, updates for toolchain changes
- Update gbdk version to 4.3.0

Docs: 4.3.0 updates

---

gbdk-support/png2asset/export_c_file.cpp
gbdk-support/png2asset/testing/ref/zgb_nums_map_2.c
gbdk-support/png2asset/testing/ref/zgb_nums_map_4.c
gbdk-support/png2asset/testing/ref/zgb_nums_map_6.c
gbdk-support/png2asset/testing/ref/zgb_nums_map_8.c

png2asset: fix num_pals member value output with use_structs + source_tileset

---

docs/pages/02_links_and_tools.md
docs/pages/06b_supported_consoles.md
docs/pages/08_faq.md
gbdk-support/png2asset/process_arguments.cpp

- Add Banjo for SMS/GG music driver
- Links to Mega Duck tech docs
- Clarify that png2asset -spr16x16 is for MSX only

Docs: misc links, tool output

---

gbdk-support/bankpack/common.h
gbdk-support/bankpack/options.c
gbdk-support/makebin/makebin.c

- And makebin: improve mbc list comment

Bankpack: Support mbc7

---

gbdk-lib/libc/targets/mos6502/nes/nes_palettes.s

* Refactor set_bkg_palette / set_sprite_palette
* Refactor set_bkg_palette_entry / set_sprite_palette_entry

NES: Refactor NES palette setting functions for smaller code

---

gbdk-lib/examples/megaduck/laptop_keyboard/src/megaduck_key2ascii.c
gbdk-lib/examples/megaduck/laptop_keyboard/src/megaduck_keyboard.c
gbdk-lib/examples/megaduck/laptop_keyboard/src/megaduck_keyboard.h
gbdk-lib/include/duck/laptop_io.h
gbdk-lib/libc/targets/sm83/duck/megaduck_laptop_io.c

- Printer command labeled and some query commands for the init result
- Run cart command labeled

MegaDuck: Updated on duck laptop IO commands, expose a few vars

---

docs/pages/02_links_and_tools.md
docs/pages/09_migrating_new_versions.md
docs/pages/10_release_notes.md
docs/pages/20_toolchain_settings.md
gbdk-support/lcc/lcc.c

- Minor LCC comment for deprecated flag

Docs: start of 4.4.0 release and migration notes, toolchain settings
