- gbdk-lib/libc/asm/gbz80/asm_string.s
- gbdk-lib/libc/asm/gbz80/crt0_rle.s
- gbdk-lib/libc/asm/gbz80/div.s
- gbdk-lib/libc/asm/gbz80/mul.s
- gbdk-lib/libc/asm/gbz80/shift.s
- gbdk-lib/libc/gb/arand.s
- gbdk-lib/libc/gb/cpy_data.s
- gbdk-lib/libc/gb/drawing.s
- gbdk-lib/libc/gb/get_bk_t.s
- gbdk-lib/libc/gb/get_data.s
- gbdk-lib/libc/gb/get_wi_t.s
- gbdk-lib/libc/gb/get_xy_t.s
- gbdk-lib/libc/gb/hiramcpy.s
- gbdk-lib/libc/gb/init_tt.s
- gbdk-lib/libc/gb/input.s
- gbdk-lib/libc/gb/mv_spr.s
- gbdk-lib/libc/gb/scroll_s.s
- gbdk-lib/libc/gb/set_bk_t.s
- gbdk-lib/libc/gb/set_prop.s
- gbdk-lib/libc/gb/set_spr.s
- gbdk-lib/libc/gb/set_wi_t.s
- gbdk-lib/libc/gb/set_xy_t.s
Only when a is obviously used afterwards
Each one of them saves 2 cycles
In rare cases I could even save 3 cycles and 1 byte
--
I test compiled gbdk-2020, but I have no project for testing functionality.
I think I found all typos, this replacement is quite monotonic.
> Replace ld (hl) dec hl with ld (hl-)

- gbdk-lib/libc/asm/gbz80/abs.s
Small improvement in abs.s, 1-2 cycles faster than previous ASM rewrite. I've tested correctness for all 16-bit numbers.
Cycle counts for JL2210's version.
Pos: 16
Neg: 23
Cycle counts for this PR.
Pos: 14
Neg: 22
> Small improvement in abs, 1-2 cycles fater than previous ASM rewrite.

- gbdk-support/lcc/lcc.c
Second part of fix for #54 
@untoxa added an initial fix in c92576df90c199c9ac44839e8830aee49e64c473, but maybe that only works on Windows. Building the colorbar sample was still failing on Linux (see below).
The problem was that the -Wm handling in lcc was adding two arguments when processing -yC instead of a single argument. -yC (and related args) don't have a trailing option value.
This also adds mention that the -Wm option exists to the command line help
Fixes this:
```
../../../bin/lcc -Wa-l -Wl-m -DGBDK_2_COMPAT -c -o colorbar.o colorbar.c
../../../bin/lcc -Wa-l -Wl-m -DGBDK_2_COMPAT -v -Wm-yC -o colorbar.gb colorbar.o
../../../bin/lcc $Id: lcc.c,v 1.6 2001/10/28 18:38:13 michaelh Exp $
"../../../"bin/sdldgb -n -i -m -g _shadow_OAM=0xC000 -g .STACK=0xDEFF -g .refresh_OAM=0xFF80 -b …
```
> Fix for #54 on Linux. (Only add one arguments to makebin for -yC and related, instead of two)

- gbdk-support/lcc/gb.c
- gbdk-support/lcc/lcc.c
Fixes #52 (introduced in commit https://github.com/Zal0/gbdk-2020/commit/4928c8884bd2cc05130bce816f203473c7cf925a)
While I'm at it, fix some other things:
* use header files to get function prototypes rather than defining them ourselves
* Include stdlib.h in gb.c to get the definition for exit
* prevent several possible overflows
* use proper types for PIDs
> Fix -S flag in LCC

- gbdk-support/lcc/gb.c
- gbdk-support/lcc/lcc.c
Not sure if there was a specific reason the default stack location got moved to 0xDEFF? 
It seems like it should be at 0xE000, which is also where the old versions of GBDK located it.
At the current location it would effectively create a block of 0x101 bytes after the stack that might go unused by default (unless explicitly specified).
> LCC: Change default stack location from 0xDEFF to 0xE000 (end of WRAM1)

- .gitignore
- gbdk-lib/include/gb/gb.h
- gbdk-lib/include/gbdk-lib.h
**NOTE : This is more of a Request For Comment / Discussion than a PR.**
The existing, old GBDK docs would really benefit from being updated. Some parts are not well or fully documented, others are out of date versus GBDK 2020 and the appearance is generally dated.
http://gbdk.sourceforge.net/doc/html/index.html
http://gbdk.sourceforge.net/doc/html/book01.html
http://gbdk.sourceforge.net/guidelines.html
A lot of the existing documentation was generated with Doxygen from the Header files. Doxygen appears to still be underactive development and is easy to use. So, it seems worth exploring whether that could continue to be a workable solution.
Here is a proof of concept to see what it might look like, both in how it affects source code and what it could look like.
- Updated and filled out …
> Update GBDK Docs

- gbdk-lib/include/time.h
Seems like the time() seconds calculation should be dividing sys_time by 60 instead of 100...?
time() is essentially using sys_time / CLOCKS_PER_SEC, and sys_time is incremented once per VBL (~60 hz). Neither 100 nor 50 match the frame rate, and so yields an incorrect seconds calculation.
I could be misunderstanding this, but it seems like it's wrong. A test showed it's off by the amount predicted by the 60hz vs 100hz difference.
> Fix time() calculation of seconds. Use 60hz instead of 100hz (or 50)

- Makefile
- docs/config/gbdk-2020-doxyfile
@untoxa 
I tested and this seems to fix the 'make docs' command on Windows + Mingw. Checked with both doxygen 1.8.17 and 1.8.20, both were ok.
> Docs: Fix doxygen 'make docs' on Windows

- Makefile
Adds minimum requirement of doxygen 1.8.17 for `make docs`
> Docs: Add doxygen version check to require at least 1.8.17 in order to ensure improved theme gets processed correctly

- gbdk-support/lcc/gb.c
- gbdk-support/lcc/lcc.c
Preface: I'm not particularly attached to this PR. No worries if it isn't desirable to merge this. Mostly doing since @JL2210 prompted a further review of why -S didn't work as advertised, which I'd started and then stopped a while back.
This seems like an alright approach, there might be other and better way to do it.
This does not attempt to block contradictory flags if there are any
@JL2210 If you can test this out and confirm it's what you expect, that would be helpful.
> Lcc: -S flag as per lcc help output - Compile only; do not assemble or link

- gbdk-support/lcc/lcc.c
Fix for #68 
Add .adb to the list of intermediate file types to delete (rmlist) so that they get cleaned up when the debug build is complete.
Currently they just get left in the default temp directory (or in the user specified temp directory if -tempdir= is used).
For reference: *.adb files are generated when -Wf--debug is specified, and are used to further generate .cdb files
> LCC: fix for #68, *.adb files aren't cleaned up when -Wf--debug is specified

- gbdk-support/lcc/gb.c
- gbdk-support/lcc/lcc.c
LCC: fix output not working if target is -o <filename>.ihx (#71 )
If the desired output is a .ihx file then the makebin step (.ihx -> .gb) needs to be suppressed and .ihx needs to be removed from the list of files to delete (rmlist).
> LCC: fix output not working if target is -o <filename>.ihx

- README.md
- gbdk-support/README
Historically, GBDK was shipped with the modified LCC described in the
book "A Retargetable C Compiler: Design and Implementation." However,
SDCC has been the actual C compiler for GBDK, and the program "lcc" is
now the wrapper of SDCC. That is, "lcc" is the compiler driver rather
a C compiler for the sake of compatibility. This patch removed
misleading descriptions about LCC.
A compiler driver is a program which invokes the other components of
the tool set to process a program. The compiler driver uses command
line arguments and source file extensions to determine which compiler
or assembler to invoke for each source file, then sequence the
resulting output through the subsequent linker and conversion
utilities, relieving the user of the burden of invoking each of these
tools …
> Clarify the use of lcc

- Makefile
CVS access was only valid for older versions of GBDK.
> Drop CVS related entries

- Makefile
Old gcc hacks are not necessary.
> Remove out-of-date gcc stuff

- Makefile
This patch specifies the predefined list for SDCC executable files for
GBDK installation. For x86_64-w64-mingw32 target, the extra DLL files
are copied as the necessary runtime.
> Improve the rules to install SDCC executables

- gbdk-support/lcc/lcc.c
The assigned variable would be nulled but not freed upon failure.
> Fix common realloc mistake

- gbdk-support/bankpack/bankpack.c
- gbdk-support/bankpack/common.h
- gbdk-support/bankpack/obj_data.c
- gbdk-support/bankpack/obj_data.h
- gbdk-support/lcc/lcc.c
@untoxa 
Adds auto-calculation of cartsize. It is rendered in stdout as "autocartsize:N", warn about fixed banks outside specified limits, fixes a recent typo in a lcc comment
(I could be wrong about this...)
For LCC it doesn't appear straightforward to capture STDOUT from the spawned bankpack child process, particularly because commands get executed in a different way between Windows and Linux.
* On Windows LCC uses _spawnvp() which is part of the API. I didn't see obvious support for capturing STDOUT from the child.
* On Linux LCC uses a custom function to emulate the behavior of _spawnvp(). With that function it may be do-able using dup2() and a pipe.
> BankPack: Calculate cart size (-cartsize)

- gbdk-lib/examples/gb/banks_autobank/Makefile
Changes example project to use MBC5 which has larger number of banks available for SDCC banked calls than MBC1 (0x1F max).
This might help reduce confusion in the future by new users by starting them with an MBC that can grow more easily.
> BankPack: Example project Makefile: Change to MBC5, fix lcc typo

- gbdk-support/lcc/Makefile
- gbdk-support/lcc/lcc.c
For #102 
- Updates version reported to 2.0
- Reports actual build date (in UTC)  instead of 2001/10/28
- Also fixes missing line break in help output
Tested on Windows and Linux.
```
$ ./lcc -v
./lcc $Id: lcc.c,v 2.0 2020/12/18 06:54:16 gbdk-2020 Exp $
```
> LCC: Update version reported to 2.0 and use actual build date

- Makefile
@untoxa 
On Windows converts WIN/MSDOS slashes to Unix style. This should fix MinGW errors when copying SDCC bins at the end of make, mentioned in #103 and introduced in #88.
Tested and working ok on Windows and Linux. Conversion is only applied on Windows.
> Makefile: Fix SDCCDIR bin copy on Windows for issue #103, remove unused as2gbmap

- README.md
OK, how about this.
- The sections are merged.
- The gbdev link that expired is updated to a new one. But would it be better to link to https://gbdev.io/chat? That way if they update the links it will still remain valid
> Readme: Consolidate Discord and Docs links, update expired gbdev discord link

- gbdk-support/bankpack/obj_data.c
- gbdk-support/bankpack/obj_data.h
The filtering of symbols to rewrite was failing to require exact match of trailing `Def0000FF`. Add an additional sscanf param for the bank number and make sure it's the one that indicates auto-banking.
> Bankpack: Fix incorrect filtering of symbols to rewrite

- gbdk-support/lcc/lcc.c
Fixllist adds flags for required addresses if not defined by the user. It was broken and always adding the built-in flag addresses, even if specified with a different value by the user. Detection for some of the address entries needed individual fixes.
- List def checking needed to be updated for spaces added between argument switch and value (possibly in cc4d79899f08faae9995210a710359ea2e3517cd). Now it advances to the next list item when testing -g and -b. If it's at the end of the list it quits. 
- Fix incorrect flag var used for .refresh_OAM
- Fix incorrect string detection for _shadow_OAM
Tested on Linux & Windows (would not expect any different on them for these changes).
> Lcc: Fix broken Fixllist() :)

- gbdk-lib/libc/_divslong.c
- gbdk-lib/libc/_modslong.c
- gbdk-lib/libc/_modulong.c
This should take care of the licensing questions in #114.
SDCC clarified and fixed up the linking exemption headers in 2010:
https://sourceforge.net/p/sdcc/code/5737/
>  device/lib/*.c: sdcc library license changed to GPL+LE
Only the updated header comments are merged in for now, it leaves the files otherwise unchanged. Later, if someone wants to spend a little time doing a review and some testing, the code changes that have occurred since then could be merged too. modslong and modulong have changed very little, but divslong has changed more (mostly variable naming).
https://sourceforge.net/p/sdcc/code/HEAD/tree/trunk/sdcc/device/lib/_modulong.c
History: https://sourceforge.net/p/sdcc/code/12015/log/?path=/trunk/sdcc/device/lib/_modulong.c …
> Lib: Pull in updated linking exemption headers from SDCC versions

- Makefile
Both host and target operating system informations were hardcoded. This
patch attempts to retrieve them via "uname -s".
> Retrieve system identifier from "uname"

- docs/config/gbdk-2020-doxyfile
- docs/config/github-markdown-theme/doxygen_extra.css
- docs/index.md
- docs/pages/banking_mbcs.md
- docs/pages/docs_index.md
- docs/pages/links_and_tools.md
- docs/pages/migrating_new_versions.md
- docs/pages/page docs_coding_guidelines.md
- docs/pages/release_notes.md
- docs/pages/sample_programs.md
- docs/pages/toolchain.md
- docs/pages/using_gbdk.md
- gbdk-lib/include/gb/drawing.h
- gbdk-lib/include/gb/hardware.h
- gbdk-lib/include/gbdk-lib.h
- gbdk-lib/include/stdio.h
@untoxa @Zal0 
This PR imports and updates some of the old GBDK general docs that were scattered in different places and formats on the sourceforge site, along with some new docs. Obsolete or irrelevant old GBDK docs were not added.
The PR does __not__ contain any generated doc updates for the changes. Those can be rendered later, there may be corrections and updates to be made beforehand.
It is a lot of text. It would benefit from more fact checking if anyone is inclined :)
The generated output can be previewed here:
https://bbbbbr.github.io/gbdk-2020/api/
-------
Something related to consider:
This is the updated docs/ root level www page. It's kinda empty looking. :) 
https://bbbbbr.github.io/gbdk-2020/
Should the docs/ root landing page be removed and have all the web traffic go …
>  Docs: Add general docs in markdown format, a couple minor header file doc updates

- gbdk-support/lcc/lcc.c
Re #118, add a convenience -debug option for lcc which turns on:  
- ` --debug` for sdcc
- `-y` (.cdb) and `-j` (.noi) for sdldgb
Also listed in lcc help output:
`-debug        turn on --debug for compiler, -y (.cdb) and -j (.noi) for linker`
lcc build and example project build tested ok on Linux & Windows
> LCC: add -debug for default compiler and linker debug flags

- docs/pages/banking_mbcs.md
- docs/pages/coding_guidelines.md
- gbdk-lib/include/gb/gb.h
- gbdk-lib/include/stdio.h
Also fix markdown page filename, fix banking size calculation
> Docs: Add guidance about passing chars to vararg functions such as printf

- Makefile
Without this, `make` tries to `cp` sdcdb twice; since my installation
of sdcc is read-only, this gives me:
```
cp: cannot create regular file '/data/auto/sources/gbdk-2020/build/gbdk/bin/sdcdb': Permission denied
```
The fix seems innocent enough, and WorksForMe (tm)
----
#
> Remove duplicate sdcdb entry.

- gbdk-support/gbcompress/Makefile
- gbdk-support/gbcompress/gbcompress.c
- gbdk-support/gbcompress/gbcompress.h
- gbdk-support/gbcompress/main.c
Previous version had fixed size output buffer that was probably fine in most cases. This adds dynamic reallocation (instead of erroring out) in case it grows beyond original output buffer size.
Also better checks to avoid input buffer overrun on decompression and simplifies decompression code a little.
> Grow output buffers if needed, better input buffer overrun checking

- gbdk-lib/libc/sprintf.c
Not sure if you'll want to merge these changes, but here's a PR just in case.
I added them because I was getting format mismatches when comparing linux console output vs GBDK BGB debug log output for the same program. GBDK2020 prints `%x` as if it was `%04X`, yet it doesn't support (fails to print) actual `%04X` when it's used.
- Ignore %0 padding and %1-9 width specifier instead of failing to print
- Support upper case X hex specifier by mapping as if it was %x (%x maps to uppercase right now anyway)
> printf: try not to fail when encountering %0... %1-9... and upper case %X

- gbdk-support/lcc/gb.c
Backport of 1a1e48b87064596bf697f959293825f72c0c780c
Allows to easily run with external SDCC snapshot / release through `--sdccbindir=`.
It's especially needed if gbdk is located at a write protected location or when it’s undesirable to fix the sdcc binaries in gbdk-2020 with symlinks.
It's analogous to the existing `--prefix=`, `--gbdklibdir=` and `--gbdkincludedir=`.
> Allow to set --sdccbindir via cli flag

- gbdk-lib/examples/gb/banks_autobank/Makefile
This is a fix for the Makefile for the time being:
- handle .rel and .o files in two separate steps, first bankpack .o -> .rel, then link .rel files
A larger fix is still needed.
When bankpack is called through lcc with "convert to .rel" ("-Wb-ext=.rel"), the link list is  passed in as ".o" and then converted to ".rel". __The problem__ is that LCC must then know to rewrite input list of files to link from ".o" into ".rel".
I'll spend more time thinking about how to fix this, but this PR should be OK for now.
> Examples: Bankpack: Interim fix for build failure

- gbdk-lib/include/gb/gb.h
the same issue occurs in the doc pages (https://zal0.github.io/gbdk-2020/docs/api/gb_8h.html#adf6ef63efc4bb4950428015c623bca14) but i cant find where to fix it in the repo lol
> fixed comment typo: immediatly -> immediately

- docs/pages/10_release_notes.md
- gbdk-lib/include/gb/metasprites.h
Docs for the metasprite API.
No docs for the command line tool in this. Maybe that comes some time after the release.
For the variation functions, maybe it should just say the following to keep it simpler. Any preference?
```
Moves metasprite to the absolute position x and y, __flipped on the X axis__
See @ref move_metasprite for more details
```
This should probably be fact-checked. :)
> Docs: metasprite

- gbdk-lib/examples/gb/banks_autobank/Makefile
Basxto merged -yoA for makebin a little while ago, so now the auto-banking example can use it instead of specifying how many ROM banks to use for makebin.
> Examples: Autobanks: switch to -yoA for makebin auto bank calculation

- docs/pages/08_faq.md
- docs/pages/20_toolchain_settings.md
- gbdk-lib/include/gb/metasprites.h
- gbdk-support/png2mtspr/png2mtspr.cpp
Some changes to address things mentioned in #172
- png2mtspr: add option to set a different default value for sprite property/attribute byte. @Zal0 any preference or comments about this?
- Document interaction between metasprites and sprite property flag, add a faq entry about it, including new png2mtspr option
Bonus: fix png2mtspr fprintf int->long compiler warnings
> Improvements for Metasprites and sprite property flags

- gbdk-support/lcc/gb.c
This turns on the deferred symbol resolution in sdasgb with the `-n` flag.
Deferred symbol resolution allows autobanked source files to utilize their own bank ID constant from within the same file. Previously it could only be accessed from other source files (since it was resolved internally to 255 before reaching the autobank processing stage).
__Requires__: SDCC build 12238 or later
See: https://sourceforge.net/p/sdcc/code/12238/
Also tidied up sdasgb defaults to a centralized location (`%asdefault%`).
Did some light testing with sdcc nightly 12246 and the examples. It seems to be working ok.
> LCC: update to always use -n for sasgb (defer symbol resolution to link time) - for autobanking

- Makefile
- gbdk-support/png2mtspr/Makefile
- gbdk-support/png2mtspr/png2mtspr.cpp
* Turns off suppression of "blank" metapsrite frames (frames composed of entirely transparent sprites). 
* Fix endless loop bug for png files taller than 255 pixels (unsigned char used for x/y coordinates), also tidy a (int) to (long int) comparison warning and harmonize the types a little more (`int` is used most by function params, so that was used)
* Also add missing tools prefix for cross-compile support in Makefile (empty and not used by default)
> Png2mtspr : empty metasprites and fix for pngs over 255 pixels in height or width

- gbdk-support/lcc/lcc.c
`-Wl-yp`/`-Wm-yp` currently makes 4.1.0's makebin segfault, which results in lcc emitting:
> lcc: fatal error in /usr/bin//makebin
> Work around segfault when using -Wl-yp

- docs/pages/20_toolchain_settings.md
- gbdk-lib/examples/gb/banks_autobank/Makefile
- gbdk-support/bankpack/bankpack.c
Makebin -yt accepts both Hex and Decimal (via stroul auto-detect), update bankpack to be the same.
* Correct wrong numeric format used in autobank example makefile, also change it's MBC type to one that has RAM to match the existing -ya4 specifier. 
* Update related toolchain arguments doc
> Bankpack: Fix -yt mbc specifier to also accept Decimal to match makebin -yt

- gbdk-support/bankpack/bankpack.c
- gbdk-support/gbcompress/main.c
- gbdk-support/ihxcheck/ihxcheck.c
Fix argument handling that might accidentally match mid-parameter, but should only match at start of parameter (bankpack, ihxcheck, gbcompress)
> Support tools: Fix argument handling

- gbdk-support/gbcompress/Makefile
- gbdk-support/gbcompress/files.c
- gbdk-support/gbcompress/files.h
- gbdk-support/gbcompress/files_c_source.c
- gbdk-support/gbcompress/files_c_source.h
- gbdk-support/gbcompress/main.c
Some optional features. No worries if there isn't agreement to merge them.
Adds:
- C source array format **output** (`--cout`) (optional variable name argument `--varname=`) 
- C source array format **input** (`--cin`) (somewhat experimental)
This removes the need to use something like bin2hex on the compressed output, and instead can write it directly.
Combined with --cin, it allows compressing some data that may only be in C source array format
> Gbcompress: add c source array format input and output

- gbdk-lib/examples/gb/linkerfile/Makefile
- gbdk-lib/examples/gb/linkerfile/Readme.md
- gbdk-lib/examples/gb/linkerfile/src/main.c
- gbdk-lib/examples/gb/template_minimal/Makefile
- gbdk-lib/examples/gb/template_subfolders/Makefile
- gbdk-support/lcc/gb.c
- gbdk-support/lcc/lcc.c
lcc changes:
- Add support for converting .ihx to .gb via lcc (suppress calling linker stages)
- If a single .ihx input is present, it will only convert .ihx to .gb
- Warn if source/obj inputs are present when .ihx is present (they won't get compiled / linked)
- Warn if more than one .ihx input is present (only use last one entered)
- Split .ihx and .gb appart in the suffixes[] list. This required a bunch of miscellaneous changes
- Separate crt0.o suppression into a new flag (`-nocrt`)
- Tidy up and simplify linker flag (-Wl-...) handling, 
- Add/improve some comments
Examples: 
- Add project showing use of linkerfile
- Path fixes for Windows make.bat output, remove quotes around path  (templates & linkerfile example)
Built and tested on Linux & Windows (build gbdk, then test linkerfile …
> Lcc fixes and improvements: ihx -> gb, linkerfile, add linkerfile example, -nocrt

- gbdk-support/lcc/gb.c
- gbdk-support/lcc/gb.h
- gbdk-support/lcc/lcc.c
An attempt to make the extension handling code easier to understand and maintain, while still keeping the definition of extensions centralized. 
Also adds some comments where the code is still harder to read.
It's more readable, but still a little awkward. Feedback or ideas to improve it more?
For example:
From: `ofile = concat(base, first(suffixes[3]));`
To: `ofile = concat(base, EXT_O);`
From: `target_is_ihx = (suffix(outfile, suffixes, 5) == 4);`
To: `target_is_ihx = (suffix(outfile, (char *[]){EXT_IHX}, 1) != SUFX_NOMATCH);`
It doesn't entirely improve code like this: (`Count number of (.c, .i, .asm, .s) files`)
From: `else if (suffix(argv[i], suffixes, 3) >= 0)`
To: `else if (suffix(argv[i], suffixes, 3) != SUFX_NOMATCH)`
> lcc: make extension handling code easier to understand

- docs/pages/20_toolchain_settings.md
- gbdk-support/lcc/gb.c
- gbdk-support/lcc/lcc.c
Adds a `-no-libs` option for lcc.
This removes the following entries from the linker stage:
`-k %libdir%%port%/ -l %port%.lib -k %libdir%%plat%/ -l %plat%.lib`
Updates the toolchain command line arguments markdown file (auto-generated)
> Lcc: add -no-libs (also rename -nocrt to -no-crt)

- gbdk-lib/include/bcd.h
- gbdk-lib/include/gb/cgb.h
- gbdk-lib/include/gb/console.h
- gbdk-lib/include/gb/drawing.h
- gbdk-lib/include/gb/far_ptr.h
- gbdk-lib/include/gb/font.h
- gbdk-lib/include/gb/gb.h
- gbdk-lib/include/gb/gbdecompress.h
- gbdk-lib/include/gb/malloc.h
- gbdk-lib/include/gb/metasprites.h
- gbdk-lib/include/gb/sample.h
- gbdk-lib/include/gb/sgb.h
- gbdk-lib/include/rand.h
- gbdk-lib/include/time.h
- gbdk-lib/libc/atoi.c
- gbdk-lib/libc/atol.c
- gbdk-lib/libc/bcd.c
- gbdk-lib/libc/gb/font.s
- gbdk-lib/libc/gb/get_t.s
- gbdk-lib/libc/gb/gprintf.c
- gbdk-lib/libc/gb/gprintln.c
- gbdk-lib/libc/gb/gprintn.c
- gbdk-lib/libc/gb/metasprites.s
- gbdk-lib/libc/gb/metasprites_flip.s
- gbdk-lib/libc/gb/rand.s
- gbdk-lib/libc/gb/set_t.s
- gbdk-lib/libc/scanf.c
- gbdk-lib/libc/time.c
In addition to #194 
Convert types for gbdk libs, but not for standard lib parts and string handling.
(UBYTE|UINT8|unsigned char) -> uint8_t
(BYTE|INT8|char) -> int8_t
(UWORD|UINT16|unsigned int) -> uint16_t
(WORD|INT16|int) -> int16_t
(ULONG|UDWORD|unsigned long) -> uint32_t
(LONG|DWORD|long) -> in32_t 
Samples all build and run.
Docs should be regenerated later to reflect new types in function declarations.
> Lib: convert to using stdint.h types instead of UINT8 / UBYTE / WORD etc Re: #162

- docs/pages/04_coding_guidelines.md
- docs/pages/08_faq.md
- gbdk-lib/include/gb/gb.h
- gbdk-lib/include/gb/metasprites.h
- Advise against blocking use of `delay()` vs every N frames
- Advise against repeated sequential calls to `joypad()`, cache result instead
- Add `float` to FAQ
- Add mention of when `metasprite_end` is used
> Minor docs edits

- Makefile
- `sdcc-clean` target appears to be leftover and invalid, removing it
- add `dist-examples-rebuild ` to [make] clean and rebuild examples in the build-output directory
- Update name at top to GBDK-2020
> Makefile: Remove one missing target (sdcc-clean), add dist-examples-rebuild 

- Makefile
- gbdk-support/bankpack/Makefile
- gbdk-support/gbcompress/Makefile
- gbdk-support/ihxcheck/Makefile
- gbdk-support/lcc/Makefile
- gbdk-support/png2mtspr/Makefile
- fix a couple incorrect lines for png2mtspr
- fix png2mtspr cross building
- remove .exe in gbdk-support on make clean for all binaries (may have been ok in Windows, was not working on linux cross builds)
Copy gbdk-support stage of cross build still isn't working, but I won't tamper with that for now.
> Makefiles: minor png2mtspr and cross-build fixes

- gbdk-lib/include/gb/hardware.h
Noticed the recent additions to `hardware.h`, decided to flesh it out by checking what other flags/helpers are implied by Pan Docs and not provided here.
> Add some helpful hardware.h defines.

- gbdk-support/lcc/gb.c
- gbdk-support/lcc/gb.h
- gbdk-support/lcc/lcc.c
- Add default rom binary extensions for all ports:platforms
- Default to rom extension format instead of .ihx when no output target is specified
- Autobanking is only called for ports:platforms which have the bankpack compose string populated
- Change makebin default flag for current z80 ports to -S
> LCC port:platform improvements

- gbdk-lib/include/asm/types.h
- Allows using `.l` and `.h` directly for the `fixed` type without requiring `.b` as a prefix (`.b.h` and `.b.l` still work of course)
@Zal0 and @untoxa  - No worries if either of you aren't into this patch
> Add simpler way of accessing high and low bytes in "fixed" union type

- Makefile
> Makefile: generate make.bat for all available platforms in build output, not just gbz80 platforms

- gbdk-support/bankpack/bankpack.c
- gbdk-support/bankpack/common.h
- gbdk-support/bankpack/obj_data.c
- gbdk-support/bankpack/obj_data.h
- Distributes banks randomly and sparsely as possible to help reveal hidden bank problems and assumptions
- Also Fix scenario where MBC flag was overriding -max bank setting
> Bankpack: Add -random for sparse random bank assignment

- docs/pages/04_coding_guidelines.md
- docs/pages/docs_index.md
- gbdk-lib/examples/ap/gb-dtmf/gb-dtmf.c
- gbdk-lib/examples/ap/metasprites/metasprites.c
- gbdk-lib/examples/gb/gb-dtmf/gb-dtmf.c
- gbdk-lib/examples/gb/metasprites/metasprites.c
- gbdk-lib/examples/gg/metasprites/metasprites.c
- gbdk-lib/examples/sms/metasprites/metasprites.c
- gbdk-lib/libc/time.c
- gbdk-support/gbcompress/gbcompress.c
There are small typos in:
- docs/pages/04_coding_guidelines.md
- docs/pages/docs_index.md
- gbdk-lib/examples/ap/gb-dtmf/gb-dtmf.c
- gbdk-lib/examples/ap/metasprites/metasprites.c
- gbdk-lib/examples/gb/gb-dtmf/gb-dtmf.c
- gbdk-lib/examples/gb/metasprites/metasprites.c
- gbdk-lib/examples/gg/metasprites/metasprites.c
- gbdk-lib/examples/sms/metasprites/metasprites.c
- gbdk-lib/libc/time.c
- gbdk-support/gbcompress/gbcompress.c
Fixes:
- Should read `updates` rather than `udpates`.
- Should read `following` rather than `followin`.
- Should read `processing` rather than `procesing`.
- Should read `large` rather than `larege`.
- Should read `documentation` rather than `documenation`.
- Should read `completely` rather than `completly`.
Semi-automated pull request generated by …
> docs: Fix a few typos

- gbdk-support/bankpack/obj_data.c
* Fixed banks were not always getting packed first due to a difference in default qsort default between mingw and regular gcc. Return more explicit sorting data to guarantee fixed areas are first (then sort by size descending)
Other changes:
* Don't show warning message when assigning a fixed bank outside of the the specified min-and-max range. Just ignore it.
* Bank overflow conditions: Just warn for fixed banks and don't error out (add them anyway, set free space to zero). Still error out and exit for auto-banked entries, thought hey should never get that far due to earlier checks.
> Bankpack fix mingw sort + change error messages

- gbdk-lib/examples/ap/linkerfile/Makefile
- gbdk-lib/examples/gb/linkerfile/Makefile
- gbdk-support/bankpack/bankpack.c
- gbdk-support/bankpack/files.c
- gbdk-support/bankpack/files.h
- gbdk-support/lcc/Makefile
- gbdk-support/lcc/gb.h
- gbdk-support/lcc/lcc.c
- gbdk-support/lcc/list.c
- gbdk-support/lcc/list.h
* When bankpack is called through lcc it will now always use linkerfile output (`-lkout=`) for passing files to the linker (all other object files and linkerfiles will get removed from the linker input)
* `-lkin=<filename>` adds a input linkerfile (can specify multiple ones)
* `-lkout=<filename>` enables linkerfile output and sets name (only one can be specified). **ALL** loaded object files, both from the command and any linkerfiles will have their name written to this single output
* Pass all input linkerfiles (from `-Wl-f<name>`) to bankpack (`-lkin=`)
* Always use linkerfile output when lcc calls bankpack (`-lkout=`)
* Use temporary file for bankpack linkerfile output name
* Clear out linker object file and linkerfile lists, then just feed in a single bankpack linkerfile
* Don't add …
> Add linkerfile support to Bankpack + LCC integration

- docs/pages/02_links_and_tools.md
I created a github action for the gbdk-2020.
This could be a great addition to this documentation page.
> Add ci/cd section with gbdk github action builder

- .github/gbdk_build_and_package.yml
- initial commit of workflow
- uses patched sms/gg sdcc binaries for Linux & Windows
- Currently points to here to repo listed below for binaries, but should be changed to a GBDK-2020 owned repo 
http://github.com/bbbbbr/gbdk2020-sdcc/releases
- Automatic builds are turned **OFF** right now - to manually trigger a build go to Actions -> click this workflow -> Run Workflow
> CI/CD: build and package GBDK-2020 on Linux / macOS / Window (x64)

- docs/pages/04_coding_guidelines.md
- docs/pages/09_migrating_new_versions.md
- docs/pages/10_release_notes.md
- gbdk-lib/include/gb/gb.h
- Updates due to change in variable initialization
- gb: make it easier to find set_tiles(), get_tiles(), set_tile_data(), set_data(), get_data() from related functions
> Docs: continuing 4.0.5 updates

- docs/config/gbdk-2020-doxyfile
- docs/pages/04_coding_guidelines.md
- docs/pages/05_banking_mbcs.md
- docs/pages/06b_supported_consoles.md
- docs/pages/09_migrating_new_versions.md
- docs/pages/10_release_notes.md
- gbdk-lib/include/asm/z80/types.h
- gbdk-lib/include/gbdk/console.h
- gbdk-lib/include/gbdk/far_ptr.h
- gbdk-lib/include/gbdk/font.h
- gbdk-lib/include/gbdk/gbdk-lib.h
- gbdk-lib/include/gbdk/incbin.h
Docs: Fix misc doxygen warnings and duplicate entries
Docs: Doxygen config: Define __PORT_gbz80
- Fixes issue where function definitions would be ignored if no valid PORT was defined
- Defaults to GB Port for documentation when required
- See: PREDEFINED = __PORT_gbz80
> Docs: updates for 4.0.5 & fix doxygen warnings/dupes

- docs/pages/06_toolchain.md
- docs/pages/08_faq.md
- docs/pages/10_release_notes.md
- gbdk-support/png2asset/readme.md
- list z80instructionSize warning as a known issue
- png2asset updates, harmonize manual and readme.md
> Docs: updates for 4.0.5

- Makefile
- docs/pages/06b_supported_consoles.md
- docs/pages/20_toolchain_settings.md
- Update some notes about building without lcc and directly using the sdcc tools
- Add sdldz80 and sdasz80 to toolchain help output page (updated main makefile to generate it, plus updated output)
> Docs: toolchain notes updates for 4.0.5

- docs/pages/20_toolchain_settings.md
- gbdk-support/gbcompress/Makefile
- gbdk-support/gbcompress/gbcompress.c
- gbdk-support/gbcompress/main.c
- gbdk-support/gbcompress/rlecompress.c
- gbdk-support/gbcompress/rlecompress.h
Fix two bugs when processing data sizes larger than 64K
- input address for read_uint16_t() was 16 bits instead of 32
- backref size was potentially larger than 64K, which wouldn't fit in it's 16 bit storage
Add block style rle compression 
- use `--alg=rle`
Update help output in tool and documentation
> Gbcompress: fixes and improvements

- gbdk-support/lcc/targets.c
* Requires GBDK-2020 patched makebin, or SDCC makebin r12748 or higher
> Lcc: Turn off Nintendo logo copy in makebin for gameboy and related clones

- docs/pages/01_getting_started.md
- docs/pages/06b_supported_consoles.md
* Getting Started: Fix naming and steps for Windows without make (compile.bat)
* Supported Consoles: Add Megaduck
> Docs: Getting Started and Supported Consoles

- docs/pages/03_using_gbdk.md
- docs/pages/06b_supported_consoles.md
- docs/pages/08_faq.md
- gbdk-lib/include/gb/gb.h
- gbdk-lib/include/gb/metasprites.h
* Fix name for BGP, OBP0, OBP1 register references
* Fix LCDC bit reference
* FAQ: note about how to relocate the start of DATA and the Shadow OAM
* Remove outdated/incorrect info about function start and end symbols for copying functions
* Note that move_metasprite_*flip() are only available for GB and related clone consoles + some trailing spaces
> Docs work 2

- gbdk-support/bankpack/Makefile
- gbdk-support/gbcompress/Makefile
- gbdk-support/ihxcheck/Makefile
- gbdk-support/lcc/Makefile
- gbdk-support/png2asset/Makefile
Set build target: MACOSX_DEPLOYMENT_TARGET=10.10
Was not able to target versions older than 10.10. In the future this minimum version may have to get increased if the CI runners for macOS is upgraded and drops support for 10.10.
> CI-CD: macOS binary compatibility fixes for older OSes

- gbdk-support/png2asset/png2asset.cpp
Adds a header const: <mapname>_TILE_ORIGIN
Tested and works using cross-platform logo example with gb, gbc, ap, gg, sms
> png2asset: maps: -tile_origin offset option for when map tiles do not start at tile 0 in VRAM

- README.md
Add Game Boy Color to line with Game Boy support. Also reorder the listing to reflect that of the [docs](docs/pages/06b_supported_consoles.md) page more accurately.
> Include CGB in Supported Consoles

- gbdk-support/lcc/lcc.c
* Split -xjn to -xj n instead of -x jn (same for -xo and -xv)
> lcc: fix handling of makebin sega -x* options

- docs/pages/08_faq.md
- gbdk-lib/examples/ap/sgb_border/border.c
- gbdk-lib/examples/ap/sgb_border/sgb_border.h
- gbdk-lib/examples/cross-platform/banks_autobank/src/banks.c
- gbdk-lib/examples/cross-platform/banks_autobank/src/srcfile_1.h
- gbdk-lib/examples/cross-platform/banks_autobank/src/srcfile_2.h
- gbdk-lib/examples/cross-platform/banks_autobank/src/srcfile_3.h
- gbdk-lib/examples/cross-platform/banks_autobank/src/srcfile_4_not-autobanked.c
- gbdk-lib/examples/cross-platform/banks_autobank/src/srcfile_4_not-autobanked.h
- gbdk-lib/examples/gb/sgb_border/border.c
- gbdk-lib/examples/gb/sgb_border/sgb_border.h
- gbdk-lib/include/gb/gb.h
- gbdk-lib/include/gb/sgb.h
Docs:
* Improve set*_based_*() description and add a FAQ entry
* Add note for set_interrupts() about critical sections
* Add note about delay that is required on startup for SGB on PAL SNES, otherwise SGB border doesn't show up
Examples:
* Convert autobanks example to use header files. Model best practices for users. This shows them how to use header files and hopefully reduces cases where .c source files get #included
> Docs & Examples: Updates for 4.0.6, SGB & Autobanking

- docs/pages/01_getting_started.md
- docs/pages/02_links_and_tools.md
- docs/pages/05_banking_mbcs.md
- docs/pages/09_migrating_new_versions.md
- docs/pages/10_release_notes.md
- docs/pages/docs_index.md
* Update 4.0.6 changelog a little more
* Docs intro page tweaks (auto-banking, megaduck)
* Initial version of Migrating-from-pre-gbdk-2020-tutorials guide
* Docs: Add link to Larolds tutorials
> Docs: Updates for 4.0.6

- docs/pages/06_toolchain.md
- docs/pages/06b_supported_consoles.md
- docs/pages/20_toolchain_settings.md
- gbdk-lib/examples/cross-platform/logo/Readme.md
- gbdk-support/png2asset/png2asset.cpp
- Notes about cross-platform Logo example
- png2asset: notes about SGB border conversion and example, update it's bpp help output
> Docs updates for 4.0.6

- Makefile
- export OS_TARGET=Win_x32; make
- export OS_TARGET=Win_x64; make
or
- SET OS_TARGET=Win_x32
- SET OS_TARGET=Win_x64
- (use exiftool on linux to verify)
- Also fixed strip executable extension during cross build
> Build: Main Maikefile: flag for cross building Win x32 or x64

- .github/workflows/gbdk_build_and_package.yml
- Makefile
Now build for both x32 and x64, requires patched SDCC Win x32 binary (has been added to https://github.com/gbdk-2020/gbdk-2020-sdcc/releases)
(cross build from Linux might be an option, but could have higher AV warnings)
Minor fix to main Makefile for windows executable extension handling
> CI/CD: Build and Package: Win x32 build into develop

- docs/pages/02_links_and_tools.md
- docs/pages/04_coding_guidelines.md
`gbdev.io/list.html` goes to 404. The new URL is `gbdev.io/resources.html`.
> [docs] Update gbdev.io URL from list.html to resources.html

- gbdk-support/gbcompress/files.c
- On windows windows fread() will auto-translate CRLF to just LF and report it as one byte read, messing up the size check. Read it as binary instead.
> Gbcompress fix read size error

- gbdk-lib/libc/rules-asxxxx.mk
- gbdk-lib/libc/targets/sm83/ap/Makefile
- gbdk-lib/libc/targets/sm83/duck/Makefile
- gbdk-lib/libc/targets/sm83/gb/Makefile
- gbdk-lib/libc/targets/z80/gg/Makefile
- gbdk-lib/libc/targets/z80/sms/Makefile
* Strip all relative paths from font filenames in each targets/CPU/Makefile
* Add additional rule for stripping ../../ from .o filename in rules-asxxxx.mk
> Fix build system bug accidentally introduced by PR#356

- Makefile
* Remove makebin from list of SDCC binaries to copy in sdcc-install build step
> Fix makebin build bug causing internal fork to get overwritten

- gbdk-lib/libc/targets/mos6502/nes/Makefile
- gbdk-lib/libc/targets/mos6502/nes/pad.s
- gbdk-lib/libc/targets/mos6502/pad_ex.s
* Add NES-specific code pad.s for reading NES joypads
* Add 6502 code pad_ex.s for reading up to 2 joypads into the joypads_t struct
> NES joypad support

- gbdk-lib/examples/cross-platform/pong/Makefile
- gbdk-lib/examples/cross-platform/pong/Makefile.targets
- gbdk-lib/libc/targets/mos6502/nes/Makefile
- gbdk-lib/libc/targets/mos6502/nes/pad.s
- gbdk-lib/libc/targets/mos6502/pad_ex.s
* Add "nes" to TARGETS in Makefile, and change platform specific flags to not use -autobank for NES
* Add nes/nes-clean to Makefile.targets
Note: Collision with pads is currently broken for NES - to-be-investigated
> Enable examples/cross-platform/pong for NES

- docs/pages/04_coding_guidelines.md
- docs/pages/06b_supported_consoles.md
- docs/pages/08_faq.md
- docs/pages/09_migrating_new_versions.md
- docs/pages/10_release_notes.md
- A little naming tidy up as well
- gbz80 to sm83 info
- calling convention change
> Docs: Initial 4.1.0 migration notes, Release notes shim

- gbdk-lib/examples/cross-platform/metasprites/Makefile
- gbdk-lib/examples/cross-platform/metasprites/Makefile.targets
- gbdk-lib/include/gbdk/metasprites.h
- gbdk-lib/include/nes/metasprites.h
- gbdk-lib/libc/targets/mos6502/nes/Makefile
- gbdk-lib/libc/targets/mos6502/nes/fill_rect_bk.s
- gbdk-lib/libc/targets/mos6502/nes/global.s
- gbdk-lib/libc/targets/mos6502/nes/metasprites.s
- gbdk-lib/libc/targets/mos6502/nes/metasprites_hide.s
- gbdk-lib/libc/targets/mos6502/nes/metasprites_hide_spr.s
* Add implementation of move_metasprite in metasprites.s
* Add implementation of hide_metasprite in metasprites_hide.s
* Add implementation of hide_sprites_range in metasprites_hide_spr.s
* Enable examples/cross-platform/metasprites for NES
> Add (non-flipped) metasprite support for NES

- docs/config/gbdk-2020-doxyfile
- docs/pages/09_migrating_new_versions.md
- gbdk-lib/include/gb/gb.h
- gbdk-lib/include/gb/gbdecompress.h
- gbdk-lib/include/gbdk/rledecompress.h
- Docs: updates for *_decompress() 
- Docs: doxygen reference fix for lcc 
- Docs: 1bpp graphics api info
-  Doxygen: update header file constant gbz80 -> sm83. Fixes initrand() doxygen warnings
> Docs: header file updates

- Makefile
- docs/pages/04_coding_guidelines.md
- docs/pages/09_migrating_new_versions.md
- gbdk-lib/examples/gb/apa_image/src/main.c
- gbdk-lib/include/gb/gb.h
- gbdk-lib/include/gb/hardware.h
- gbdk-lib/include/gb/metasprites.h
- gbdk-lib/include/stdio.h
Docs: header content and misc
- Notes about explicit cast to printf, sprintf, etc
- Clarify set_*_submap x,y parameters
- Link hide_sprite, hide_sprites_range, HIDE_SPRITES
- Note VBK_REG is cgb only
Makefile: Update global version to 4.1.0 (affects docs)
Examples: APA: change incorrect use of constant
> Docs 4 1 0 headers

- gbdk-lib/include/nes/nes.h
- Haven't found a good way to avoid these otherwise so far aside from suppressing them in all but one declaration
- warning: argument 'xxx' from the argument list of yyyhas multiple @param documentation sections
- Some warnings still remain (joypad_ex, etc)
> Docs: NES: remove some doxygen @params due to dupe warnings

- gbdk-support/ihxcheck/areas.c
- gbdk-support/ihxcheck/areas.h
- gbdk-support/ihxcheck/ihx_file.c
* A multiple write to the same address must occur. The address where the overlap ends is used as BANK.
* There must also be a write which spans multiple banks, the ending address of that must match BANK. The starting addresses is the OVERFLOW-FROM BANK.
> ihxcheck: Check and warn for bank overflows under specific conditions

- docs/pages/03_using_gbdk.md
- gbdk-lib/include/gb/gb.h
Also add:
- References to add_low_priority_TIM
- Note about duration of LCD ISRs when called once per each scanline
> Docs: Updates for number of installable interrupt handlers

- gbdk-lib/examples/gb/template_minimal/Makefile
This was resulting in a `-p` directory being created.
```bat
REM Automatically generated from Makefile
mkdir -p obj
.\vendor\gbdk\bin\lcc   -c -o obj\main.o src\main.c
.\vendor\gbdk\bin\lcc   -c -o obj\dungeon_map.o res\dungeon_map.c
.\vendor\gbdk\bin\lcc   -c -o obj\dungeon_tiles.o res\dungeon_tiles.c
.\vendor\gbdk\bin\lcc   -o obj\Example.gb obj\main.o obj\dungeon_map.o obj\dungeon_tiles.o 
```
```bat
REM Automatically generated from Makefile
mkdir obj
.\vendor\gbdk\bin\lcc   -c -o obj\main.o src\main.c
.\vendor\gbdk\bin\lcc   -c -o obj\dungeon_map.o res\dungeon_map.c
.\vendor\gbdk\bin\lcc   -c -o obj\dungeon_tiles.o res\dungeon_tiles.c
.\vendor\gbdk\bin\lcc   -o obj\Example.gb obj\main.o obj\dungeon_map.o obj\dungeon_tiles.o 
```
> GB Examples: Remove invalid -p option from mkdir in compile.bat

- gbdk-support/png2asset/png2asset.cpp
Fixing an issue when trying to use source_tileset and keep_palette_order. The pointer would go out of scope, resulting in a  '_The palette's for your source tileset and target image do not match._' error. The solution, as recommended by @bbbbbr was a malloc & memcpy instead.
> Fixing source tileset palette copy with keep_palette_order

- gbdk-support/bankpack/Makefile
- gbdk-support/bankpack/bankpack.c
- gbdk-support/bankpack/common.h
- gbdk-support/bankpack/obj_data.c
- gbdk-support/bankpack/obj_data.h
- gbdk-support/bankpack/options.c
- gbdk-support/bankpack/options.h
- Add -reserve=<banks>:<size>]
- Banks value is in decimal
- Size value is in hex
- Start putting option commands in options.c instead of with bank processing code
- Refactor
- Move more option code into options.c
- Improve variable naming and scope a little
> Bankpack: Add -reserve=<banks>:<size> + option refactor

- gbdk-lib/libc/targets/mos6502/nes/crt0.s
- gbdk-lib/libc/targets/mos6502/nes/set_bk_attributes.s
* Remove _attribute_shadow from DATA segment
* Place _attribute_shadow at 0x188 to coexist with CPU stack / vram transfer buffer
* Remove assumption on _attribute_shadow being 256-byte aligned in _set_bkg_attributes, by replacing OR of address / index with addition
> NES: Fix bug with global initialized data being initialized to zero

- gbdk-lib/libc/targets/mos6502/nes/crt0.s
- gbdk-lib/libc/targets/mos6502/nes/set_bk_attributes.s
- gbdk-lib/libc/targets/mos6502/nes/set_bk_ts.s
* Add helper subroutines ppu_stripe_begin(_horizontal/vertical), ppu_stripe_end and ppu_stripe_write_byte
* Update _set_bkg_tiles to use the new ppu_stripe_* subroutines
* Add _set_bkg_tiles code path for vertical stripes, and prefer this when width < height
* Update _flush_shadow_attributes_update_row to use the new ppu_stripe_* subroutines
> NES: Refactor nametable writes to use indirect writes via the vram transfer buffer when screen is not blanked

- gbdk-lib/examples/cross-platform/rle_map/src/main.c
* Change "data" from a 2D array of 32x18 to a 1D array of 18, decreasing RAM usage from 576 to 18
* Make scroll update code decompress to the same column
> Optimize RAM use in cross-platform/rle_map

- gbdk-lib/libc/targets/mos6502/nes/crt0.s
- gbdk-lib/libc/targets/mos6502/nes/fill_rect_bk.s
- gbdk-lib/libc/targets/mos6502/nes/set_data.s
* Fix bug with .ppu_stripe_begin subtracting 1 x8-cycle too many
* Remove decrementing of *__crt0_drawListNumDelayCycles_x8 .ppu_stripe_write_byte, and make .ppu_stripe_end calculate cycles from number of bytes written
* Update _set_tile_data to write the 16 bytes of a tile via ppu_stripe* functions when display is on
* Update _fill_bkg_rect to write bytes via the ppu_stripe_ functions, and prefer vertical stripes when height > width
> NES: Support setting tile data indirectly via vram transfer buffer when display is on

- gbdk-lib/examples/cross-platform/rle_map/Makefile
- gbdk-lib/examples/cross-platform/rle_map/Makefile.targets
- gbdk-lib/include/gbdk/rledecompress.h
- gbdk-lib/libc/targets/mos6502/nes/Makefile
- gbdk-lib/libc/targets/mos6502/rle_decompress.s
* Add 6502 assembly RLE implementation in gbdk/libc/targets/mos6502/rle_decompress.s
* Enable examples/cross-platform/rle_map for NES
> NES: Add support for RLE decompression

- LICENSE
- docs/pages/02_links_and_tools.md
- docs/pages/08_faq.md
- gbdk-lib/include/gb/gb.h
- gbdk-lib/include/nes/nes.h
- licenses/LICENSE_crashhandler
- Update crash handler license to zlib
- FAQ entry for license requrements of a compiled ROM
- Link to sdas / aslink manual
-Docs: Incorrect reference for set_bkg_submap
> Docs 4.1.0 - Licensing, SDAS manual, fix wrong link

- docs/pages/05_banking_mbcs.md
- docs/pages/10_release_notes.md
- gbdk-lib/examples/cross-platform/banks_autobank/Makefile
- gbdk-lib/examples/gb/sgb_border/Readme.md
- gbdk-lib/examples/gb/sgb_border/border.c
- gbdk-support/lcc/lcc.c
- When -autobank is enabled adds "-yo", "A" to makebin list if no other "-yo*" entry is present
- Correct typo in docs related to makebin flags
Also, a SGB docs typo
> LCC: if -autobank enabled, add -yoA if -yo not specified for makebin

- gbdk-lib/examples/cross-platform/randtest/Makefile
- gbdk-lib/examples/cross-platform/randtest/Makefile.targets
- gbdk-lib/include/rand.h
- gbdk-lib/libc/asm/mos6502/Makefile
- gbdk-lib/libc/asm/mos6502/rand.s
* Port rand / randw / initrand from sm83 to mos6502
* Point arand / initarand at rand / initrand, to conserve memory
* Update cross-platform/randtest to build for nes
> NES: Add random number generation to NES target

- .github/workflows/gbdk_build_examples.yml
- README.md
- Save copies of the built examples as artifacts
- Change recommended and started by @michel-iwaniec + my Windows runner fix
> CI/CD: Build Examples: Upload build artifacts

- gbdk-support/lcc/targets.c
- See: https://sourceforge.net/p/sdcc/patches/435/
- Intended as temporary workaround
> LCC: Turn on  --no-peep for NES target to work around SDCC issue

- gbdk-lib/libc/targets/mos6502/nes/global.s
* Port FAST_DIV8 and FAST_MOD8 macros in gbdk-lib/libc/targets/z80/sms/global.s to gbdk-lib/libc/targets/mos6502/nes/global.s
> NES: Add FAST_DIV8 / FAST_MOD8 macros

- gbdk-lib/examples/cross-platform/large_map/Makefile
- gbdk-lib/examples/cross-platform/large_map/src/large_map.c
* Remove set_2pp_palette(COMPAT_PALETTE(11,5,4,3)) call, to make colors more consistent across all targets
* Replace hardcoded width / height of 20 / 18 with DEVICE_SCREEN_WIDTH / DEVICE_SCREEN_HEIGHT
* Add blanking of leftmost column if DEVICE_SCREEN_BUFFER_WIDTH == DEVICE_SCREEN_WIDTH
* Add helper functions update_column_left / right and update_row_top / bottom, to define update column / row per-target
* Update WRAP_SCROLL for SMS's 224-high nametable - and default to NES's 240-high nametable for all other targets
* Add SCROLL_Y_OFFSET constant for adjusting final scroll on a per-target basis, to hide scrolling artifacts
* Enable sms target in Makefile
> SMS: Enable examples/cross-platform/large_map for SMS

- gbdk-support/makebin/makebin.c
* Change iNES mapper field from mapper#2 (UNROM) to mapper#30 (UNROM-512)
* Change iNES mapper 4-screen bit, to specify single-screen nametable mirroring
> NES: Switch to single-screen mirroring in makebin, for easier scrolling logic / less attribute shadow RAM

- gbdk-lib/libc/targets/mos6502/nes/crt0.s
- gbdk-support/lcc/targets.c
* Make generic CODE segment start at 0x8000
* Introduce new segment 8kB CODEFIXED at 0xE000 dedicated to crt0, leaving remaining 24kB to CODE
> NES: Increase total ROM space, as a work-around for lack of bank-switching

- gbdk-lib/examples/cross-platform/large_map/Makefile
- gbdk-lib/examples/cross-platform/large_map/Makefile.targets
- gbdk-lib/libc/targets/mos6502/nes/Makefile
- gbdk-lib/libc/targets/mos6502/nes/global.s
- gbdk-lib/libc/targets/mos6502/nes/set_tile_submap.s
* Add NES implementation of set_bkg_submap in gbdk-lib/libc/targets/mos6502/nes/set_tile_submap.s
* Enable examples/cross-platform/large_map for nes target
> NES: Add large map scrolling support

- gbdk-support/lcc/lcc.c
- Unmatched '-' entries need to fall through to option() in gb.c for additional testing
> LCC: fix for --sdccbindir= broken in commit c1398c2afaa90af8d8c945f39c2c02be531b95f2

- gbdk-lib/include/gb/gb.h
- gbdk-lib/include/msx/msx.h
- gbdk-lib/include/nes/nes.h
- gbdk-lib/include/sms/sms.h
- gbdk-lib/libc/targets/mos6502/nes/metasprites.s
- gbdk-support/png2asset/png2asset.cpp
* Update printing of METASPR_ITEM in png2asset to extract X/Y flip and palette number, print them as symbolic names S_FLIPX, S_FLIPY and S_PAL(...)
* (...and adjust output formatting to one METASPR_ITEM per line, for better readability)
* Add #define for S_PAL to gb.h, nes.h, msx.h and sms.h
* Remove "TODO:" comments from gbdk-lib/libc/targets/mos6502/nes/metasprites.s
> png2asset: Make props in generated metasprites cross-platform

- gbdk-lib/libc/targets/mos6502/nes/nes_palettes.s
* Replace .define:s aliasing to _set_bkg_palette_PARM_3 with duplicated labels
> NES: Fix compiler bug with missing parameter allocation in set_*_palette_* functions

- gbdk-lib/include/nes/metasprites.h
- gbdk-lib/libc/targets/mos6502/nes/metasprites.s
* Introduce global __current_base_prop and apply as offset in move_metasprite_* asm implementation
* Update move_metasprite_* functions in metasprites.h to set __current_base_prop global
> NES: Refactor metasprite functions to match GB refactoring

- gbdk-lib/examples/cross-platform/metasprites/src/metasprites.c
- gbdk-lib/include/gb/gb.h
- gbdk-lib/include/msx/msx.h
- gbdk-lib/include/nes/nes.h
- gbdk-lib/include/sms/sms.h
* HARDWARE_SPRITE_CAN_FLIP_H -> HARDWARE_SPRITE_CAN_FLIP_X
* HARDWARE_SPRITE_CAN_FLIP_V -> HARDWARE_SPRITE_CAN_FLIP_Y
> Rename HARDWARE_SPRITE_CAN_FLIP_* defines to align with new flipx/flipy naming

- gbdk-lib/examples/cross-platform/metasprites/Makefile
- gbdk-lib/examples/cross-platform/metasprites/src/metasprites.c
* Extend rot variable to switch between palettes after every X/Y/XY flip rotation, and apply to move_metasprite_* calls
* Setup pink, cyan and green palettes for GBC/NES to visualize switching
* Enable gbc as target in Makefile
> Add sub-palette switching to cross-platform/metasprites example (for GBC and NES)

- gbdk-lib/examples/cross-platform/metasprites/Makefile
- gbdk-lib/examples/cross-platform/metasprites/src/metasprites.c
- gbdk-lib/include/sms/metasprites.h
- gbdk-lib/libc/targets/z80/sms_metasprites.s
* Change sms_metasprites to have 4 permutations for flipping combinations, using a generic macro for function bodies
* Change examples/cross-platform/metasprites to duplicate uploaded tiles by X and Y depending on HARDWARE_SPRITE_CAN_FLIP_X/Y defines
* Change examples/cross-platform/metasprites to use 8x8 sprites, to make all duplicated tiles fit tile memory on sms/gg
* Remove hide / show metasprite functionality in examples/cross-platform/metasprites
* Move rotation to A button, to make compatible with 2-button SMS joypad
> Cross-platform metasprite flipping support:

- gbdk-lib/examples/cross-platform/logo/src/main.c
- gbdk-lib/include/nes/nes.h
- gbdk-lib/libc/targets/mos6502/nes/Makefile
- gbdk-lib/libc/targets/mos6502/nes/crt0.s
- gbdk-lib/libc/targets/mos6502/nes/flush_attributes.s
- gbdk-lib/libc/targets/mos6502/nes/set_bk_attributes.s
- gbdk-support/png2asset/png2asset.cpp
* Move _flush_shadow_attributes subroutine to its own file flush_attributes.s
* Add bitfield _attribute_column_dirty, and add handling of dirtied columns to _flush_attributes
* Update cross-platform/logo/src/main.c to use 8x8 coordinate system for NES
png2asset:
* Fix bug in PackMapAttributes where height was always being set to width
* Refactor BuildPalettesAndAttributes palette search into its own function FindOrCreateSubPalette
* Change BuildPalettesAndAttributes to force subPalIndex to 0 instead of causing segfault when there's too many colors for an attribute region
* Add new function AlignMapAttributes to ensure map is properly aligned for set_bkg_submap
* Change #define MAP_ATTRIBUTES_WIDTH/HEIGHT to use new 8x8 coordinate system
> NES: Refactor attributes to use 8x8 attribute coordinate system, to be more consistent with other platforms

- gbdk-lib/libc/targets/mos6502/nes/crt0.s
* Add call to subroutine _hide_sprites_range using full 256-byte range
* Write OAMADDR and OAMDMA registers
> NES: Initialize OAM at reset

- gbdk-lib/examples/cross-platform/logo/src/main.c
- gbdk-lib/include/gb/gb.h
- gbdk-lib/include/sms/sms.h
- gbdk-support/png2asset/png2asset.cpp
* Add inline functions set_bkg_attributes / set_bkg_submap_attributes to gb.h
* Make these functions temporarily switch in attribute memory, call set_bkg_tiles / set_bkg_submap, then switch out attribute memory
* Update examples/cross-platform/logo to use set_bkg_attributes for all platforms having attributes
* Remove NES-specific round-to-two in examples/cross-platform/logo to simplify example, as the logo image fulfills this criteria
> GBC: Add cross-platform attribute setting functions

- gbdk-lib/examples/cross-platform/metasprites/src/metasprites.c
- gbdk-lib/include/nes/metasprites.h
- gbdk-lib/libc/targets/mos6502/nes/Makefile
- gbdk-lib/libc/targets/mos6502/nes/metasprites.s
- gbdk-lib/libc/targets/mos6502/nes/metasprites_common.s
- gbdk-lib/libc/targets/mos6502/nes/metasprites_flipx.s
- gbdk-lib/libc/targets/mos6502/nes/metasprites_flipxy.s
- gbdk-lib/libc/targets/mos6502/nes/metasprites_flipy.s
* Change x / y parameters of move_metasprite* function definitions from uint8 to int16
* Update move_metasprite* to do 16-bit math, and reject hardware sprites outside screen
* Move flip[x/y] move_metasprite* functions into separate files for independent linking
* Move .move_metasprite_prologue / _epilogue functions into new file metasprites_common.s
> NES: Add metasprite clipping support

- gbdk-support/png2asset/png2asset.cpp
* Update CmpIntColor comparison functor to use RGB values as less-significant bits
* Fix inconsistent indentation
> png2asset: Fix bug with incorrect palettes when different colors have same luma

- gbdk-support/png2asset/Makefile
- gbdk-support/png2asset/image_utils.cpp
- gbdk-support/png2asset/image_utils.h
- gbdk-support/png2asset/png2asset.cpp
- gbdk-support/png2asset/png2asset.h
**Fix bit packed indexed pngs bit with less than 8 bits**
- Turn off lodepng conversion when indexed bpp is less than 8
- lodepng was modifying the pixel palette color values when unpacking indexed color images with less than 8 bits per pixel
- Fix the issue by manually unpacking to the expected indexed 8bpp
- See this earlier commit which tried to solve a related issue the easy way, which didn't end up working with lodepng https://github.com/gbdk-2020/gbdk-2020/commit/dbf093fdb1ee154714ef5e0812fbdadfd96ce589
**Repair Indexed Pal**
- Requires -keep_palette_order to be in use
- Tries to repair tile palettes for indexed color images
- Leaves tiles alone if they have no palette errors
- Errors out if it cannot find a palette which matches all colors in a tile
Might consider another mode …
> Png2asset: fix bit packed indexed images, -repair_indexed_pal feature

- gbdk-lib/include/nes/hardware.h
* Change defines in hardware.h to use volatile __at(addr) for regs, and extern volatile for shadow regs
> NES: Fix PPU register definitions

- docs/pages/01_getting_started.md
Add instructions how to un-quarantine unsigned binaries for macOS users. Also fixed `MacOS` -> `macOS` to match Apple styling / branding.
> Update 01_getting_started.md for macOS users

- Makefile
The gbdk-lib-install-ports has an unwritten dependency on the gbdk-lib-build target. the gbdk-lib-install-ports target fails if built before the gbdk-lib-build target. In a non-parallelized build, these two targets are built in the right order and the build works fine. In a parallelized build, a race condition causes the targets to build in the wrong order.
> Fix gbdk-lib-install-ports target dependencies

- gbdk-support/lcc/targets.c
- Resolves PR #489 identified by @RetroGamer02
> lcc: Use GG Export region code (6) when building for Game Gear

- docs/pages/05_banking_mbcs.md
- docs/pages/06b_supported_consoles.md
- docs/pages/10_release_notes.md
- gbdk-support/makebin/makebin.c
- Fix missing info that yoN and yaN are also used for SMS to actually set number of banks
- Notes in docs
(Requested by Calindro)
> Makebin: Warn if RAM banks specified and file size of ROM is less than the 64K required to enable them with in emulators

- docs/config/github-markdown-theme/doxygen_extra.css
- docs/pages/04_coding_guidelines.md
- docs/pages/06b_supported_consoles.md
- docs/pages/08_faq.md
- docs/pages/09_migrating_new_versions.md
- docs/pages/10_release_notes.md
- gbdk-lib/include/gb/gb.h
- Improve doxygen @note styling
- Convert several entries of "Note:" to @note
- Fix incorrect link anchor for mac os security warning in faq
- Add some missing SDCC versions to older release notes
> Docs: Add warning about reading from VRAM, etc

- gbdk-lib/libc/targets/mos6502/nes/Makefile
- gbdk-lib/libc/targets/mos6502/nes/crt0.s
- gbdk-lib/libc/targets/mos6502/nes/global.s
- gbdk-lib/libc/targets/mos6502/nes/set_data.s
- gbdk-lib/libc/targets/mos6502/nes/vram_transfer_buffer.s
* Move helper functions for transfer buffer from crt0 into dedicated file vram_transfer_buffer.s
* Update various variables to consistently use __vram_transfer_buffer* naming
> NES: Move transfer buffer code out of crt0

- Makefile
Selectively copy the suitable sdcc dll based on windows 32/64 bit using a couple different tests for win32. Win 64 is the default fallback.
> Build: win32-win64 SDCC DLL copy

- gbdk-lib/libc/targets/mos6502/font.s
- gbdk-lib/libc/targets/mos6502/nes/Makefile
- gbdk-lib/libc/targets/mos6502/nes/crt0.s
- gbdk-lib/libc/targets/mos6502/nes/global.s
- gbdk-lib/libc/targets/mos6502/nes/set_tile.s
- gbdk-lib/libc/targets/mos6502/nes/vram_transfer_buffer.s
* Remove old writeNametableByte implementation
* Add _set_vram_byte which replaces writeNametableByte, but can append to old stripe in both directions
* Rename: .crt0_textStringBegin -> __vram_transfer_buffer_pos_old
* Remove unused variable __crt0_textPPUAddr
* Add set_tile.s file with implementation for set_bkg_tile_xy, calling _set_vram_byte. Update Makefile.
> NES: Add support for set_bkg_tile_xy / set_vram_byte

- Makefile
- docs/pages/03_using_gbdk.md
- docs/pages/04_coding_guidelines.md
- docs/pages/05_banking_mbcs.md
- docs/pages/06_toolchain.md
- docs/pages/10_release_notes.md
- gbdk-lib/include/gb/gb.h
- gbdk-lib/include/msx/msx.h
- Mention reading from VRAM is not supported on the NES by GBDK
- Small section on the compression tools
- Minor banking notes
- Document default startup LCDC settings for the Game Boy
- Fix a few typos and var names
> Docs 4 2 0

- gbdk-lib/libc/asm/mos6502/rand.s
- gbdk-lib/libc/targets/mos6502/nes/crt0.s
- gbdk-lib/libc/targets/mos6502/nes/global.s
- gbdk-lib/libc/targets/mos6502/nes/sdcc_bcall.s
- gbdk-lib/libc/targets/mos6502/nes/set_bk_attributes.s
- gbdk-lib/libc/targets/mos6502/nes/vram_transfer_buffer.s
- gbdk-support/lcc/targets.c
* Remove unused byte row_dirty_mask from OSEG in set_bk_attributes.s
* Reduce size of OSEG segment from 48 to 16 bytes
* Reduce size of __crt0_NMITEMP from 4 to 3 bytes, and set it to start at ___SDCC_m6502_ret4 (no functions should have return values > 32bit)
* Redefine .tempA in sdcc_bcall.s to use SDCC temp location __TEMP+7
* Redefine  __vram_transfer_buffer_tempt to use SDCC location __TEMP+6
* Redefine .tmp to point at __TEMP (SDCC temporary zeropage usage)
> NES: Reduce use of zeropage

- gbdk-lib/libc/targets/mos6502/nes/metasprites_common.s
- gbdk-lib/libc/targets/mos6502/nes/metasprites_hide_spr.s
* Move ___render_shadow_OAM from metasprites_common.s to metasprites_hide_spr.s
* Change module name of metasprites_hide_spr.s from "Metasprites" to "Sprites" to allow linking it separately
> NES: Trim sprite modules

- gbdk-lib/libc/targets/mos6502/nes/crt0.s
- gbdk-lib/libc/targets/mos6502/nes/global.s
- gbdk-lib/libc/targets/mos6502/nes/nes_palettes.s
* Change __crt0_paletteShadow segment from _ZP to _BSS in crt0.s
* Update WRITE_PALETTE_SHADOW macro and set_*_palette subroutines to not use zeropage syntax
* Adjust VRAM_DELAY_CYCLES_X8 in global.s to adjust for WRITE_PALETTE_SHADOW taking 25 (~= 24 ) CPU cycles more
> NES: Move palette shadow from zeropage to regular RAM

- gbdk-lib/libc/targets/mos6502/nes/set_tile.s
- gbdk-lib/libc/targets/mos6502/nes/vram_transfer_buffer.s
* Change incorrectly named function parameter _set_vram_byte_PARM_3 -> _set_vram_byte_PARM_2
* Add implementation for get_bkg_xy_addr, re-using existing set_bkg_tile_xy address calculation
> NES: set_vram_byte / get_bkg_xy_addr fixes

- gbdk-lib/libc/targets/mos6502/nes/crt0.s
- gbdk-lib/libc/targets/mos6502/nes/lcd.s
* Initialize both _INITIALIZER -> _INITIALIZED and _XINIT -> _DATA segments, for maximum compatibility
* Update lcd.s to use these segments
* Fix bug __crt0_setPalette causing overwriting of initialized segment
> NES: Fix recent regression caused by improper initialization of jmp_to_VBL_isr / jmp_to_LCD_isr and palette

- gbdk-lib/libc/targets/mos6502/color.s
- gbdk-lib/libc/targets/mos6502/font.s
- gbdk-lib/libc/targets/mos6502/nes/crt0.s
- gbdk-lib/libc/targets/mos6502/nes/lcd.s
- gbdk-lib/libc/targets/mos6502/nes/metasprites_hide_spr.s
* Update source files to use _XINIT / _DATA instead of _INITIALIZER / _INITIALIZED
* Fix bug with __crt0_setPalette causing overwriting of initialized segment
> NES: Fix recent regression caused by improper initialization of jmp_to_VBL_isr / jmp_to_LCD_isr

- gbdk-lib/examples/cross-platform/logo/src/main.c
- gbdk-lib/include/gb/gb.h
- gbdk-lib/include/nes/nes.h
- gbdk-lib/include/sms/sms.h
- gbdk-lib/libc/targets/mos6502/nes/Makefile
- gbdk-lib/libc/targets/mos6502/nes/crt0.s
- gbdk-lib/libc/targets/mos6502/nes/set_attribute.s
- gbdk-lib/libc/targets/mos6502/nes/set_bk_attributes.s
- gbdk-lib/libc/targets/mos6502/nes/set_tile_submap_attributes.s
- gbdk-lib/libc/targets/z80/set_tile.s
* Add dedicated NES function set_bkg_attribute_xy_nes16x16 for setting an individual (shadow) attribute in gbdk-lib/libc/targets/mos6502/nes/set_attribute.s
* Add inline adapter NES function set_bkg_attribute_xy, which calls set_bkg_attribute_xy_nes16x16
* Change NES functionality to call _flush_shadow_attributes from wait_vbl_done
* Remove calls to _flush_shadow_attributes in set_bkg_attributes and set_bkg_submap_attributes
* Add dedicated SMS/GG function set_attribute_xy in gbdk-lib/libc/targets/z80/set_tile.s
* Add inline adapter GBC function set_bkg_attribute_xy in gbdk-lib/include/gb/gb.h
> Add support functions for setting an individual map attribute

- gbdk-lib/examples/cross-platform/large_map/Makefile
- gbdk-lib/examples/cross-platform/logo/res/NES/GBDK_2020_logo.png.meta
- gbdk-lib/examples/cross-platform/logo/src/main.c
- gbdk-lib/include/gb/gb.h
- gbdk-lib/include/nes/nes.h
- gbdk-lib/include/sms/sms.h
- gbdk-lib/libc/targets/mos6502/nes/Makefile
- gbdk-lib/libc/targets/mos6502/nes/set_data.s
- gbdk-lib/libc/targets/mos6502/nes/set_native_data.s
- gbdk-support/png2asset/png2asset.cpp
- gbdk-support/png2asset/png2asset.h
* Update gbdk-lib/include/gb/gb.h to forward set_bkg_native_data / set_sprite_native_data to set_bkg_data / set_sprite_data functions
* Update gbdk-lib/include/sms/sms.h to forward set_bkg_native_data / set_sprite_data to set_bkg_4bpp_data / set_sprite_4bpp_data
* Add implementation for set_bkg_native_data / set_sprite_native_data in gbdk-lib/libc/targets/mos6502/nes/set_native_data.s
* Update gbdk-lib/include/nes/nes.h to include function declarations for set_bkg_native_data / set_sprite_native_data
* Update gbdk-lib/inlcude/nes/nes.h to implement set_native_tile_data in terms of set_bkg_native_data / set_sprite_native_data
* Update gbdk-lib/inlcude/nes/nes.h to implement set_tile_data in terms of set_bkg_data / set_sprite_data
* Remove old (/broken for indirect mode) code for …
> Add set_bkg_native_data / set_sprite_native_data functions to allow using native tile format with set_bkg_data / set_sprite_data functionality

- gbdk-lib/examples/cross-platform/banks/Makefile
- gbdk-lib/examples/cross-platform/banks_autobank/Makefile
- gbdk-lib/examples/cross-platform/banks_farptr/Makefile
- gbdk-lib/examples/cross-platform/banks_nonintrinsic/Makefile
- gbdk-lib/examples/cross-platform/large_map/Makefile
- gbdk-lib/examples/cross-platform/scroller/Makefile
- gbdk-support/bankpack/bankpack.c
- gbdk-support/bankpack/common.h
- gbdk-support/bankpack/options.c
- gbdk-support/bankpack/options.h
- gbdk-support/lcc/targets.c
* Update bankpack to have a new command-line parameter -mapper to supply mapper info for NES target (copy-n-paste of -mbc parameter implementation)
* Update gbdk-support/lcc/targets.c to call bankpack for NES target with -mapper=30 (still hard-coding Mapper30 as the mapper for now)
* Update examples/cross-platform to not supply nonsense "-Wl-yt0x1B" parameter for nes build
> NES: Remove need for dummy GB mbc parameter for banking when using NES target

- gbdk-lib/include/asm/mos6502/string.h
* Add simple #define in gbdk-lib/include/asm/mos6502/string.h to make memcpy equal __memcpy asm version
> NES: Fix missing memcpy implementation for nes target

- gbdk-lib/examples/cross-platform/libc_memcpy/Makefile
- gbdk-lib/examples/cross-platform/libc_memcpy/Makefile.targets
- gbdk-lib/examples/cross-platform/libc_memcpy/src/libc_memcpy.c
* Make test execute memcpy, memmove and memset
* Make test do two benchmarks for memcpy with 150 and 300 bytes, to identify < 256-bytes length optimizations
> Add cross-platform test for exercising libc memcpy/memmove/memset functions in string.h

- gbdk-support/makebin/makebin.c
- For emulator RAM bank mapper support
- Improvement for warning added in 32c1e97
> Makebin: If ROM auto-size enabled and SMS/GG has RAM banks, auto bump ROM size to 64K

- gbdk-lib/include/asm/mos6502/provides.h
* Change USE_C_STRCMP in gbdk-lib/include/asm/mos6502/provides.h to 0
> NES: Change nes target to use asm implementation of strcmp function

- README.md
- docs/ChangeLog
- docs/pages/06b_supported_consoles.md
- docs/pages/10_release_notes.md
- docs/pages/20_toolchain_settings.md
- gbdk-lib/include/gb/gb.h
- gbdk-lib/include/msx/msx.h
- gbdk-lib/include/nes/nes.h
- gbdk-lib/include/sms/sms.h
- Docs: some rough NES info in supported consoles pages
- More release notes
- Updated toolchain settings (via make docstools)
- Update console un-defines for platform header files
- Docs: 4.2 text file chaneglog
- Bonus: changelogs for some ancient versions
> Docs: 4.2.0 updates + update undefs for platform header files

- docs/config/gbdk-2020-doxyfile
- docs/pages/06_toolchain.md
- gbdk-lib/examples/gb/hicolor/Readme.md
- gbdk-lib/include/gbdk/emu_debug.h
- Also move comment for function inside platform ifdef
- Also add sprite limit per scanline note for gb hi-color example
> Docs: doxygen: define NINTENDO when parsing headers. fixes EMU_profiler_message() not showing up in docs

- gbdk-lib/libc/targets/mos6502/nes/set_bk_ts.s
* Add __map_tile_offset to OSEG in libc/targets/mos6502/nes/set_bk_ts.s
* Add __map_tile_offset to fetched tile in libc/targets/mos6502/nes/set_bk_ts.s
> NES bugfix: Actually apply _map_tile_offset for set_bkg_based_tiles

- gbdk-lib/libc/targets/mos6502/nes/crt0.s
* Replace subroutine __crt0_clearRAM with a one-time-use macro CRT0_CLEAR_RAM
* Make sure macro clears stack page as well as other pages
> NES vram transfer buffer bugfix: Make sure to clear stack page on reset

- gbdk-lib/include/nes/nes.h
- gbdk-lib/libc/targets/mos6502/nes/global.s
- gbdk-lib/libc/targets/mos6502/nes/pad.s
- gbdk-lib/libc/targets/mos6502/pad_ex.s
* Reverse order of bits in joypad byte and bitmasks for buttons, to conform to more common order in nesdev
* Bump MAX_JOYPADS definition in joypad_ex.s from 2 to 4
* Add label read_joypad_no_strobe, to avoid repeated strobing when reading multiple controllers
* Update joypad_ex function to call read_joypad_no_strobe repeatedly for as many controllers as initialized in joypads_t struct
* Unroll joypad reading loop for less cycles and no clobbering of Y register
> NES: Fix support for 4-player controllers using fourscore

- .github/workflows/gbdk_build_and_package.yml
- .github/workflows/gbdk_build_examples.yml
- gbdk-lib/include/asm/mos6502/types.h
- gbdk-lib/include/asm/sm83/types.h
- gbdk-lib/include/asm/z80/types.h
- gbdk-lib/include/nes/nes.h
- gbdk-lib/libc/targets/mos6502/far_ptr.s
- gbdk-lib/libc/targets/mos6502/font.s
- gbdk-lib/libc/targets/mos6502/mode.s
- gbdk-lib/libc/targets/mos6502/nes/crt0.s
- gbdk-lib/libc/targets/mos6502/nes/fill_rect_bk.s
- gbdk-lib/libc/targets/mos6502/nes/lcd.s
- gbdk-lib/libc/targets/mos6502/nes/metasprites.s
- gbdk-lib/libc/targets/mos6502/nes/metasprites_flipx.s
- gbdk-lib/libc/targets/mos6502/nes/metasprites_flipxy.s
- gbdk-lib/libc/targets/mos6502/nes/metasprites_flipy.s
- gbdk-lib/libc/targets/mos6502/nes/nes_palettes.s
- gbdk-lib/libc/targets/mos6502/nes/set_1bit_data.s
- gbdk-lib/libc/targets/mos6502/nes/set_attribute.s
- gbdk-lib/libc/targets/mos6502/nes/set_bk_attributes.s
- gbdk-lib/libc/targets/mos6502/nes/set_bk_ts.s
- gbdk-lib/libc/targets/mos6502/nes/set_data.s
- gbdk-lib/libc/targets/mos6502/nes/set_native_data.s
- gbdk-lib/libc/targets/mos6502/nes/set_tile.s
- gbdk-lib/libc/targets/mos6502/nes/set_tile_submap.s
- gbdk-lib/libc/targets/mos6502/nes/set_tile_submap_attributes.s
- gbdk-lib/libc/targets/mos6502/nes/vram_transfer_buffer.s
- gbdk-lib/libc/targets/mos6502/pad_ex.s
- gbdk-lib/libc/targets/mos6502/rle_decompress.s
- gbdk-support/lcc/targets.c
* Update gbdk_build_and_package.yml and gbdk_build_examples.yml to use gbdk-4.2.0-Next SDCC build
* Update nes.h to declare all gbdk functions with the new __no_overlay_locals function attribute
* Introduce new dedicated 16-byte overlay segment GBDKOVR, and make all assembly functions use this instead of OSEG
* Update LCC file targets.c to reserve space for both OSEG and GBDKOVR
> Reduce zeropage use for locals, by making gbdk-nes functions use its own dedicated overlay segment instead of SDCC's overlay segment

- gbdk-support/png2asset/process_arguments.cpp
when i printed the values of the default_props on windows i got crazy values. when i set the default to 0, my map was matching the map of the camera_sgb_border.c sent to me by @bbbbbr .
> defaulting default props to zero

- gbdk-support/png2asset/export.cpp
- gbdk-support/png2asset/main.cpp
- gbdk-support/png2asset/process_arguments.cpp
- gbdk-support/png2asset/process_arguments.h
png2asset: fix segfault and wrong data size on -bin export for SGB (and likely SMS)
- Make sure there is attrib data before trying to bin export it
- SGB and SMS pack attribute data into maps, so can't assume maps are 1 byte per tile in -bin mode. Added args.map_entry_size_bytes for determining size to use
png2asset: -bin mode: fix -tiles_only and -maps_only
- Make -bin export mode honor request to skip map or tile data export
> Png2asset: -bin mode: fix sgb export, honor -maps_only, -tiles_only

- gbdk-lib/libc/targets/mos6502/nes/crt0.s
* Remove b_wait_frames symbol from crt0.s
> NES: Remove unused definition

- gbdk-lib/libc/targets/z80/gb_decompress.s
- gbdk-lib/libc/targets/z80/rle_decompress.s
on Z80 in some cases `jp` would be faster than `jr`
this change optimize decompression for speed
observerd improvments:
RLE (cycles without/with)
1177/1149 (2.37%) - `rle_decompress(data, MAP_DATA_HEIGHT);` from rle_map example (also depends on data up to 3%)
GB (cycles without/with)
162358/160190 (1.34%) - `gb_decompress(monalisa_tiles_comp, buffer)` from gbdecompress example
> Z80 jumps optimization for rle/gb decompressors

- gbdk-support/png2asset/Makefile
- gbdk-support/png2asset/export.cpp
- gbdk-support/png2asset/image_data.cpp
- gbdk-support/png2asset/image_utils.cpp
- gbdk-support/png2asset/image_utils.h
- gbdk-support/png2asset/main.cpp
- gbdk-support/png2asset/map_attributes.cpp
- gbdk-support/png2asset/map_attributes.h
- gbdk-support/png2asset/maps.cpp
- gbdk-support/png2asset/metasprites.cpp
- gbdk-support/png2asset/png2asset.h
- gbdk-support/png2asset/png_image.h
- gbdk-support/png2asset/process_arguments.cpp
- gbdk-support/png2asset/process_arguments.h
- Add processing_mode for gating behavior for only source tilesets or main image
- Don't push map and metasprite index entries for source tileset images entries
- Remove unused source_tileset_image
- Fix failing to load main image after source tileset in indexed mode by clearing image data beforehand (loading quietly failed otherwise)
- Fix comparison of source tileset palette with main image palette
- Fix mis-matched palette export criteria between C header and C source file
- Re-add minimal logging to terminal of source tileset info found
- Improve source tileset conditional readbility with has_source_tilesets flag
- Remove some unused function parameters
- Re-sort default param init to match header declaration. No value changes.
> png2asset: fix -source_tileset

- gbdk-lib/examples/cross-platform/large_map/Makefile
- gbdk-lib/examples/cross-platform/large_map/src/large_map.c
Support an initial camera position other than 0,0 in the large map example
- Required some reordering of var init and improvement of the initial full screen draw
- Came out of work with @EdvinDraw, who also suggested updating the example app
> Example: large map: support changing the initial camera position

- gbdk-support/png2asset/maps.cpp
Palette id was missing in the attributes for displaying multi palette background on SMS
> SMS tilemap attributes set upper palette bit

- gbdk-lib/libc/targets/mos6502/nes/crt0.s
- gbdk-lib/libc/targets/mos6502/nes/vram_transfer_buffer.s
* Move unrolled-loop address calculation from vblank execution to buffer preparation, saving 8 cycles per stripe
* Add +1 to address and start with NOP unrolled loops with a padding byte, to keep using zero as buffer terminator
Note: This also fixes a bug with glitchy scrolling when running out of available cycles before filling up the vram transfer buffer space.
> NES: Slight optimization of transfer buffer stripe setup cost

- gbdk-lib/libc/targets/mos6502/nes/vram_transfer_buffer.s
* Rename VRAM_HDR_LENGTH -> VRAM_HDR_JMPADDR to reflect change to use address in place of length
* Add helper macro LENGTH_TO_JMPADDR to avoid code duplication
* Make sure stripe appending code uses LENGTH_TO_JMPADDR before size comparison with old buffer
> NES: Transfer buffer optimization follow-up fix / rename

- gbdk-support/png2asset/metasprites.cpp
- gbdk-support/png2asset/process_arguments.cpp
- gbdk-support/png2asset/process_arguments.h
Empty tiles are those which are entirely filled with color 0 for the given palette.
Under the hood this turns on:
- args->keep_duplicate_tiles = true
- args->keep_empty_sprite_tiles = true
This is not applicable to maps because they (already) do not discard tiles even if they are filled entirely with color zero. 
Also fix missing else statement and warn about unrecognized args
> png2asset: -sprite_no_optimize (keep empty tiles, keep duplciate tiles)

- docs/doxygen_search_override.js
Search format regex must replace all formatting instances, not just first. Otherwise matching will fail.
Example: `set_bkg_tiles` was returning zero results. Now fixed.
> Docs: fix some missed search results

- gbdk-support/bankpack/bankpack.c
- gbdk-support/bankpack/obj_data.c
- gbdk-support/bankpack/obj_data.h
- gbdk-support/bankpack/options.c
- gbdk-support/bankpack/options.h
- Example: -banktype=105:LIT
- Only matching object files will be assigned to the bank
- Error if object with fixed bank num clashes with assigned bank type for that bank
> Bankpack: -banktype arg, allow forcing a given bank type to CODE or LIT

- gbdk-support/png2asset/image_data.cpp
- gbdk-support/png2asset/main.cpp
- gbdk-support/png2asset/maps.cpp
- gbdk-support/png2asset/maps.h
- gbdk-support/png2asset/metasprites.cpp
- gbdk-support/png2asset/png2asset.cpp
- gbdk-support/png2asset/png2asset.h
- gbdk-support/png2asset/png_image.h
- gbdk-support/png2asset/process_arguments.cpp
- gbdk-support/png2asset/process_arguments.h
- `-entity_tileset  (maps only) mark matching tiles counting from 255 down, entity patterns not exported`
- Intended for (Cross)ZGB alternative for GBTD/GBMB entity map assignment
- Move source tileset extraction out of Map() and MetaSprite() conversion functions into dedicated, simpler function shared with entity tileset extraction
- Does not currently warn if tile count for source tileset + map tileset clashes with entity tileset allocation
> png2asset: add -entity_tileset feature (intended for maps only)

- gbdk-lib/libc/targets/mos6502/nes/crt0.s
- gbdk-lib/libc/targets/mos6502/nes/global.s
NES: Optimize CRT0 zeropage usage
* Remove __crt0_ScrollHV. This is redundant with single-screen mirroring
* Remove __crt0_NMI_insideNMI. NMI time should be deterministic and re-entry should not be possible.
(user-installed LCD handler assumption could break this assumption, but is planned to be moved to vsync call)
> NES: Optimize CRT0 zeropage usage

- gbdk-lib/examples/cross-platform/display_system/src/display_system.c
- gbdk-lib/include/gb/gb.h
- gbdk-lib/include/msx/msx.h
- gbdk-lib/include/nes/nes.h
- gbdk-lib/include/sms/sms.h
- gbdk-lib/libc/targets/mos6502/nes/crt0.s
- gbdk-lib/libc/targets/mos6502/nes/global.s
- gbdk-lib/libc/targets/z80/gg/global.s
- gbdk-lib/libc/targets/z80/msxdos/global.s
- gbdk-lib/libc/targets/z80/sms/global.s
NES: Add PAL support
* Add new zeropage variable _system_bits to indicate NTSC/PAL/Dendy system
* Modify init code to detect NTSC/PAL/Dendy via cycle counting, storing result in _system_bits
* Modify fake-LCD-ISR delays in NMI handler to accommodate PAL timings
Cross-platform:
* Change existing SYSTEM_NTSC / SYSTEM_PAL defines in sms.h to SYSTEM_60HZ / SYSTEM_50HZ, and copy them to gb.h / nes.h / msx.h
* Add new cross-platform function get_system for all ports, to query whether running on a 60Hz or 50Hz system
* Add minimal cross-platform display_system example to exercise get_system
> NES: Add PAL support

- gbdk-support/png2asset/export_c_file.cpp
- gbdk-support/png2asset/testing/ref/zgb_nums_map_2.c
- gbdk-support/png2asset/testing/ref/zgb_nums_map_4.c
- gbdk-support/png2asset/testing/ref/zgb_nums_map_6.c
- gbdk-support/png2asset/testing/ref/zgb_nums_map_8.c
- Was not emitting extra_tiles due to includeTileData behavior
- Update related test references
> png2asset: fix use structs + source tileset + extra-tiles were found condition

- docs/pages/06b_supported_consoles.md
* Remove "(the mapper2 subset of Mapper30)" comment (single-screen mirroring is not supported by Mapper2)
> Docs: Correct information NES part of "Supported consoles"

- gbdk-support/png2asset/export_c_file.cpp
- gbdk-support/png2asset/testing/ref/zgb_color_indexed_nums_map_2.c
- gbdk-support/png2asset/testing/ref/zgb_color_indexed_nums_map_4.c
- gbdk-support/png2asset/testing/ref/zgb_color_nums_map_2.c
- gbdk-support/png2asset/testing/ref/zgb_color_nums_map_4.c
- gbdk-support/png2asset/testing/ref/zgb_nums_map_2.c
- gbdk-support/png2asset/testing/ref/zgb_nums_map_4.c
- gbdk-support/png2asset/testing/ref/zgb_nums_map_6.c
- gbdk-support/png2asset/testing/ref/zgb_nums_map_8.c
> png2asset: incorrect tile count for use_structs + source_tileset when there are excess tiles

- gbdk-lib/examples/cross-platform/banks_nonintrinsic/src/banks_nonintrinsic.c
The main iss ue looks like it was that the area assigned is DATA_0 when the relevant vars are in DATA_1:
```C
// define array of pointers in RAM2 to the variables that are RAM2
// there is a flaw in compiler that disallows pointers into banks to be in the other banks
// details: https://sourceforge.net/p/sdcc/bugs/2995/
DATA_0 int * const CODE_1 addendum_ptr[2] = {&addendum2_ram, &addendum3_ram};
```
So when it goes to perform the calculation, it tries to pull all the vars from RAM bank 0 instead of some from 0 and some from 1. 
```C
printf("1+2+4+8=0x%x", (int)(addendum0 + addendum1_ram + (*addendum_ptr[0]) + (*addendum_ptr[1])));
```
Also renamed a lot of the vars and updated some comments to make it easier to understand what memory regions they are stored in and what is going on.
> examples: nonintrinsic: fix sram banks and make easier to understand

- docs/pages/06b_supported_consoles.md
- gbdk-lib/examples/cross-platform/scroller/src/text_scroller.c
- gbdk-lib/include/nes/nes.h
- gbdk-lib/libc/targets/mos6502/nes/crt0.s
- gbdk-lib/libc/targets/mos6502/nes/global.s
* Refactor .delay_to_lcd_scanline to not use Y register. Remove outdated comments.
* Move .jmp_to_LCD_isr call to vsync routine, and have it copy shadow PPU register values to a buffer
* Add MAX_LCD_ISR_CALLS define to limit the deferred PPU register write buffer size
* Add .do_lcd_ppu_reg_writes for writing buffer aligned to hblank, and calls to .delay_to_lcd_scanline
* Make .do_lcd_ppu_reg_write restore Y-scroll for start-of-frame after every update, to mitigate glitches in lag frames
* Have LCD at scanline#0 be treated as a special-case, where VBL shadow values are replaced without adding to the buffer
* Re-introduce variable to skip NMI as __crt0_disableNMI, and set it in vsync during buffer building
Update text_scroller example:
* Fix NES-version of code to do multiple splits like …
> NES: Add deferred hblank system for fake LCD ISRs

- gbdk-lib/examples/cross-platform/bcd/Makefile
- gbdk-lib/include/gbdk/bcd.h
- gbdk-lib/include/nes/bcd.h
- gbdk-lib/libc/asm/mos6502/Makefile
- gbdk-lib/libc/asm/mos6502/bcd.s
* Copy gbdk-lib/include/gb/bcd.h to gbdk-lib/include/nes/bcd.h
* Add bcd asm implementation in libc/asm/mos6502/bcd.s
* Update bcd.h to accept NES target
* Update examples/cross-platform/bcd to build for nes
> NES: Add BCD support

- gbdk-lib/examples/cross-platform/metasprites/src/metasprites.c
- gbdk-lib/examples/cross-platform/platformer_template/src/player.c
- gbdk-lib/libc/targets/mos6502/nes/nes_palettes.s
* Move misplaced "adc #16" instruction in nes_palettes.s
* Update metasprites and platformer_template examples to use the new 0..3 indexing
> NES: Fix bug with set_sprite_palette indexing. Sprite palettes are now indexed from 0..3 instead of 4..7

- gbdk-lib/libc/Makefile
- C errors to halt the build. sdcc returns error code 1 when failing on a syntax error, but sdas* returns error code 2 for syntax errors (even though that error code seems to be meant for incorrect arguments instead)
- So translate error codes to 1 in all cases in order to ensure the loop exits and halts the build
> build: fix asm lib errors not halting build

- gbdk-lib/libc/targets/mos6502/nes/crt0.s
NES: Fix bug with fake LCD ISR occurring at scanline 0 causing next LCD ISR to be 1 line up
* Make sure that *.lcd_scanline_previous is initialize as -1 for the special case of scanline 0
> NES: Fix bug with fake LCD ISR occurring at scanline 0 causing next LCD ISR to be 1 line up

- gbdk-lib/examples/cross-platform/scroller/src/text_scroller.c
* Make fill_bkg_rect to happen *after* an explicit initialization of font system (otherwise the printf causes a font load which in turn causes a screen clear)
> text_scroller example: Fix problem with '*' fill characters not appearing on GG/SMS

- gbdk-lib/examples/cross-platform/scroller/src/text_scroller.c
* Fix incorrect Y offset for NES in text scroller example
> * Fix incorrect Y offset for NES in text scroller example

- gbdk-lib/include/gb/gb.h
Adds a mention to the docs that HIDE_BKG and SHOW_BKG do not work while running in CGB mode, the relevant bit instead overrides all background/window priority over the sprite layer, see Pandocs 4.4
> Mention that HIDE_BKG/SHOW_BKG don't work on CGB

- gbdk-lib/libc/targets/mos6502/nes/crt0.s
* Move label jumped to upwards, so if-less-than-reached-scanline check still happens for special-case
> NES: Fix problem with deferred LCD isr special-case at scanline 0 not working unless _lcd_scanline was changed by LCD handler

- .github/workflows/gbdk_build_and_package.yml
- .github/workflows/gbdk_build_examples.yml
Reverts gbdk-2020/gbdk-2020#686
SDCC 14865 introduces codegen errors for GB targets (though it does fix a NES target codegen problem)
> Revert "CI/CD: Update to sdcc 14865" - Roll back to 14635

- gbdk-support/png2asset/export_c_file.cpp
If the source tileset includes duplicate palette information, the exporter will exclude the redundant palettes. However, the exporter was checking if i != 0 to check for the first time through the loop, and this is not true in the case of the source_tileset excluding redundant palettes. This was generating a leading comma in the output, which causes a syntax error.
> Palette Generation broken when using -source_tileset option

- gbdk-lib/examples/cross-platform/platformer_template/src/common.c
- gbdk-lib/examples/cross-platform/rle_map/Makefile
- gbdk-lib/examples/gb/apa_image/Makefile
- gbdk-lib/examples/gb/galaxy/galaxy.c
- gbdk-lib/examples/gb/gbprinter/Makefile
- Some incorrect flags and combos of flags
- cross_platform/rle_map: error: can't open build/sms/rledecompress.noi: No such file or directory
- cross_platform/platformer_template: in function setBKGPalettes unreferenced function argument : 'count',  'palettes'
- gb/galaxy: overflow in implicit constant conversion
- gb/apa_image and gb/gbprinter: Argument "-bpp2" not recognized
> Examples: Fix some warning messages

- gbdk-support/lcc/gb.c
- gbdk-support/lcc/lcc.c
The obsolete options are not supported by the current compiler
> lcc: Remove obsolete options from help, warn if found

- gbdk-support/png2asset/map_attributes.h
- gbdk-support/png2asset/maps.cpp
- Support 512 tiles via alternate tile bank on GBC attribute bit
- Make excess tile count warning less spammy. Reduce to single notice instead of one notice per tile over the limit
- Add warning for SMS when over 512 tiles
- Combine excess tile count warning and origin warning
Currently requires splitting tile pattern data into two separate loads, one for each VRAM bank
> png2asset: support 512 tiles via alternate tile bank on GBC

- gbdk-support/romusage/src/bank_templates.c
- gbdk-support/romusage/src/banks.c
- gbdk-support/romusage/src/banks.h
- gbdk-support/romusage/src/banks_print.c
- gbdk-support/romusage/src/cdb_file.c
- gbdk-support/romusage/src/common.c
- gbdk-support/romusage/src/common.h
- gbdk-support/romusage/src/ihx_file.c
- gbdk-support/romusage/src/list.c
- gbdk-support/romusage/src/map_file.c
- gbdk-support/romusage/src/noi_file.c
- gbdk-support/romusage/src/rom_file.c
- gbdk-support/romusage/src/rom_file.h
- gbdk-support/romusage/src/romusage.c
- `-b:HEXVAL:[...]` Set hex bytes treated as Empty in ROM files (.gb/etc) (default `FF`(255), ex use 255 AND 0: `-b:FF:00`
- Improve error messaging
- Allow filename at any location in option arguments
- `-nMEM` Hide memory regions with case sensitive substring (ex hide all RAM: `-nMEM:RAM`)
> romusage: upgrade from 1.2.8 to 1.3.0

- gbdk-lib/libc/targets/mos6502/nes/flush_attributes.s
* Make sure that each column re-adds PPU lo offset instead of storing it
* Wrap functionality in a macro WRITEVERT
> NES: Fix bug with multiple column attribute updates

- gbdk-lib/include/nes/nes.h
- gbdk-lib/libc/targets/mos6502/nes/set_tile_submap_attributes.s
* Add +1 before shift in inline function set_bkg_submap_attributes
* Add-with carry after right-shift of width in set_bkg_submap_attributes_nes16x16
> NES: Fix bugs with non-multiple-of-2 (/4) map width in set_bkg_submap_attributes

- docs/pages/05_banking_mbcs.md
- gbdk-support/bankpack/options.c
- gbdk-support/makebin/makebin.c
- Source info (pandocs) looks accidentally wrong
- No Rumble, no RAM, no Battery - just ACCELEROMETER and EEPROM
> Update and correct docs and comments related to MBC7

- gbdk-lib/examples/cross-platform/logo/Makefile
- gbdk-lib/examples/cross-platform/logo/Readme.md
- gbdk-lib/examples/cross-platform/logo/res/CGB/GBDK_2020_logo.png.meta
This is a less disruptive attempt at making the logos example a little more obvious for beginners.
This does three small things:
* Changes default png2asset arguments for GBC logo to use -noflip. The reasoning is that the GBC build for this example project defaults to GB and GBC compatibility (LCC flag -Wm-yc), so the default behavior for the image processing should match.
* Updates the readme with a little more context, and a note about noflip should the user need to remove the option for space efficiency reasons
* Adds the ability to set the rom title in the cartridge header
> Improve logo example

- gbdk-support/romusage/src/bank_templates.c
- gbdk-support/romusage/src/common.h
- gbdk-support/romusage/src/map_file.c
- gbdk-support/romusage/src/noi_file.c
- gbdk-support/romusage/src/romusage.c
- Experimental support for GBDK's flavor of NES (`-p:NES1"`) .noi/.map files
> romusage: upgrade from 1.3.0 to 1.3.1

- gbdk-lib/libc/targets/mos6502/nes/set_1bit_data.s
Replace direct PPUADDR / PPUDATA writes with calls to _set_vram_byte.
> NES: Fix bug with set_bkg_1bpp_data not working in buffered mode

- docs/pages/06b_supported_consoles.md
- gbdk-lib/examples/cross-platform/irq/Makefile
- gbdk-lib/examples/cross-platform/irq/src/irq.c
- gbdk-lib/examples/cross-platform/scroller/src/text_scroller.c
- gbdk-lib/include/nes/hardware.h
- gbdk-lib/include/nes/nes.h
- gbdk-lib/libc/targets/mos6502/nes/crt0.s
- gbdk-lib/libc/targets/mos6502/nes/global.s
- gbdk-lib/libc/targets/mos6502/nes/lcd.s
- Add add_TIM / remove_TIM functions to nes.h
- Refactor implementation in lcd.s to support add_TIM / remove_TIM
- Add TMA_REG / TIMA_REG / TAC_REG vars to emulate GB hardware timer register
- Add call to TIM function at end of NMI handler in crt0.s, and make it use TMA_REG / TIMA_REG vars
- Add implementation for set_interrupts in lcd.s, replacing JMP instruction with RTS when disabled
- Enable NES target in examples/cross-platform/irq and replace delay(1000) call with 60 vsyncs
- Update examples/cross-platform/scroller and examples/cross-platform/irq to use set_interrupts
- Update documentation to describe use-cases and limitations of TIM handler
> NES: Timer interrupt emulation + support for set_interrupts(...)

- Makefile
- docs/pages/06_toolchain.md
- gbdk-support/lcc/gb.c
- gbdk-support/lcc/targets.c
- gbdk-support/makebin/makebin.c
- gbdk-support/makenes/Makefile
- gbdk-support/makenes/makenes.c
- Move all .nes header related functionality into a new utility gbdk-support/makenes
- Update LCC to use makenes for .postproc member of build process, with mapper30 header parameters hard-coded for now
- Update makefiles to build makenes
> NES: Move .nes header functionality out of makebin

- gbdk-lib/libc/targets/mos6502/nes/crt0.s
- gbdk-lib/libc/targets/mos6502/nes/global.s
NES: Double-buffered deferred LCD ISR support for less graphics glitches, at expense of more RAM usage.
- Define new constant .MAX_DEFERRED_ISR_CALLS as .MAX_LCD_ISR_CALLS+1
- Refactor vsync function for double-buffering, and have it flip the read index at completion
- Refactor .do_lcd_ppu_reg_writes, and rename to .do_hblank_writes
- Remove scroll glitch mitigation in .do_hblank_writes, as no longer needed
- Redefine __lcd_isr_ arrays sizes as 2*.MAX_DEFERRED_ISR_CALLS
- remove redundant ZP variable __crt0_disableNMI, as no longer needed
- TAB -> space conversion
> NES: Double-buffered deferred LCD ISR support

- docs/pages/06b_supported_consoles.md
- docs/pages/09_migrating_new_versions.md
- gbdk-lib/examples/cross-platform/scroller/src/text_scroller.c
- gbdk-lib/include/nes/hardware.h
- gbdk-lib/libc/targets/mos6502/nes/crt0.s
- Change definition of _lcd_scanline to be -1 less than current, aligning with GB LYC register
- Change definition of _bkg_scroll_y to match GB's SCY, being relative to current scanline
- Refactor do_hblank_writes, delay_fractional and delay_to_scanline subroutines in crt0
- Add "#define LYC_REG" and "#define LY_REG" as aliases of _lcd_scanline
- Add #defines for SCX and SCY to alias _bkg_scroll_x / _bkg_scroll_y shadow variables
- Change text scroller example to use LYC_REG / SCX / SCY instead of _lcd_scanline / move_bkg, remove redundant #ifdefs
- Add subtle shake in y direction to text scroller example, to check that GB / NES coordinates match
> NES: Align coordinates and scanline counting in LCD ISR implementation with GB, add SCX / SCY / LYC defines

- Makefile
- Works around issue where the sdld linker tries to create matching .rst files in the gbdk install dir where it finds the empty crt0.lst, causing builds to fail if the user lacks permissions for that directory
This is to address #725 
However, a downside to this is that for any build it will always generate this warning per platform:
`?ASlink-Warning-<cannot open> : "../../../lib/gb/crt0.lst"`
We could modify the patch to either output No Warning or something less severe such as:
`?ASlink-Info-<cannot open> : "../../../lib/gb/crt0.lst"`
> Build: Remove creation of empty crt0.lst files in build output

- .github/workflows/gbdk_build_and_package.yml
- Build: change to SDCC 4.5.0 15267 binaries (with updated win32 DLL to fix error)
- Build: Change to Linux 22.04 runner, 20.04 discontinued (for Linux 64 bit intel builds)
> Build: change to SDCC 4.5.0 15267 binaries, linux 22.04 runner

- docs/pages/06b_supported_consoles.md
- gbdk-lib/examples/cross-platform/irq/src/irq.c
- gbdk-lib/include/gb/gb.h
- gbdk-lib/include/nes/nes.h
- gbdk-lib/libc/targets/mos6502/nes/crt0.s
- Backup and restore REGTEMP area when calling TIM ISR in vblank
- Update irq example to use #pragma nooverlay for tim handler
- Add warning and explanation about having to use #pragma for TIM handlers in NES section of docs
> NES: Make sure TIM ISR handlers are thread-safe

- gbdk-lib/libc/targets/mos6502/nes/lcd.s
- Replace incorrect code copying jmp address's opcodes with the actual address
> NES: Fix bug in ISR removal

- docs/pages/06b_supported_consoles.md
- gbdk-lib/libc/targets/mos6502/nes/Makefile
- gbdk-lib/libc/targets/mos6502/nes/crt0.s
- gbdk-lib/libc/targets/mos6502/nes/deferred_isr.s
- gbdk-lib/libc/targets/mos6502/nes/global.s
- Move code for deferred isr buffer building to separate function .deferred_isr_run in file deferred_isr.s
- Introduce function .deferred_isr_reset to write shadow regs as first (VBL) buffer entry
- Add new subroutine .deferred_isr_reset_and_init that runs .deferred_isr_reset and .deferred_isr_run twice
- Drain buffer when DISPLAY_OFF is called, by making sure a single NMI execution happens before screen is turned off in vblank
- Change DISPLAY_OFF to write only DISPLAY_OFF flag and PPUMASK, but leave shadow_PPU_MASK unchanged
- Call .deferred_isr_reset_and_init in DISPLAY_ON when display changes from off to on
- Make DISPLAY_ON run run VBL / LCD handlers to reinitialize buffers when display switches from off to on
- Change early-out in NMI handler to rely on DISPLAY_OFF flag instead of …
> NES: Refactor display_on / display_off and deferred isr code

- docs/ChangeLog
- docs/pages/10_release_notes.md
- gbdk-support/bankpack/files.c
- File descriptor/handle leak from non-closure during format detection
- Also don't open the file twice, just once
> Bankpack: Fix bug with large file count

- docs/pages/06b_supported_consoles.md
- gbdk-lib/examples/cross-platform/irq/src/irq.c
- gbdk-lib/include/nes/nes.h
- gbdk-lib/libc/targets/mos6502/nes/Makefile
- gbdk-lib/libc/targets/mos6502/nes/crt0.s
- gbdk-lib/libc/targets/mos6502/nes/global.s
- gbdk-lib/libc/targets/mos6502/nes/timer_isr.s
- Move TIM ISR emulation to dedicated function .tim_emulation and dedicated file timer_isr.s
- Make TIM ISR emulation save entirety of ALL_REGTEMPS_BEGIN to ALL_REGTEMPS_END
- Improve emulation to allow average TIM rate to be faster compared to vblank rate
- Add support for consistent average TIM rate on PAL, for a less system-dependent timer
- Add support for different base dividers defined by GB-like TAC_REG variable
- Add defines values for "vblank parity mode" to global.s and nes.h
- Update crt0 init code to set TMA_REG to vblank parity mode correctly for PAL/Dendy
- Update documentation, describing the improved GB TIM emulation and vblank parity mode
- Update cross-platform IRQ example to better showcase the emulation
> NES: Improve TIMER interrupt emulation

- .github/workflows/gbdk_build_examples.yml
- gbdk-support/lcc/gb.c
- gbdk-support/lcc/lcc.c
- Use bool to indicate postproc stage present instead of setting char pointer to null then later calling strlen on possible null pointer
- Was able to reproduce the issue somewhat reliably on Windows
- This change seems to resolve the issue
Also: turn on GBDK_DEBUG=1 for github example building
> lcc: fix sometimes incorrect detection of postproc step

- Makefile
- gbdk-lib/examples/cross-platform/large_map/src/large_map.c
- gbdk-lib/examples/cross-platform/rle_map/src/main.c
- gbdk-lib/include/nes/hardware.h
- gbdk-lib/include/nes/nes.h
- gbdk-lib/libc/targets/mos6502/nes/crt0.s
- gbdk-lib/libc/targets/mos6502/nes/flush_attributes.s
- gbdk-lib/libc/targets/mos6502/nes/global.s
- gbdk-lib/libc/targets/mos6502/nes/platform_cfg.s
- gbdk-lib/libc/targets/mos6502/nes/set_attribute.s
- gbdk-lib/libc/targets/mos6502/nes/set_bk_attributes.s
- gbdk-lib/libc/targets/mos6502/nes/set_bk_ts.s
- gbdk-lib/libc/targets/mos6502/nes/set_tile.s
- gbdk-lib/libc/targets/mos6502/nes/set_tile_submap.s
- gbdk-lib/libc/targets/mos6502/nes/set_tile_submap_attributes.s
- gbdk-support/lcc/targets.c
- Introduce platform configuration, mainly to define tilemap layout NES_TILEMAP_[F|H|V|S] in platform_cfg.s
+ Add NES_TILEMAP_S|H|V|F setting for tilemap layout, and hard-code to NES_TILEMAP_S for now
+ Add NES_LOMEM setting to enable current default of using part of stack instead of BSS for attribute shadow buffer
+ Edit Makefile to copy platform_cfg.s (if it exists) to platform directory after build
- Updates to attribute shadow buffer and dirty bits:
+ Add NUM_NT define for number of nametables used by a layout, and AT_SHADOW_WIDTH/_HEIGHT to denote the variable dimensions
+ Add convenience defines NT_2W / NT_2H to quickly test whether tilemap layout is two screens wide / high
+ Define _attribute_shadow and _attribute_row/_column_dirty in terms of NUM_NT
+ Update flush_attributes to …
> NES: Add support for various tilemap layout (mirroring) configurations
